from pathlib import Path
from html import escape
from urllib.parse import quote

ROOT = Path('/mnt/data/pddg-redesign')
BASE = 'https://ahmadmahmood11.github.io/pddg-cybersecurity'

COMPANY = {
    'name': 'Pinnacle Digital Defense Group',
    'short': 'PDDG',
    'phone': '301-532-1463',
    'email': 'Info@pddg.io',
    'address': '5457 Twin Knolls Rd, Ste 300, PMB 1019, Columbia, MD 21045',
    'hours': 'Monday–Friday, 8 AM–7 PM ET',
    'tagline': 'Risk-driven cybersecurity assessments, clear reporting, and practical remediation guidance for regulated and operationally sensitive organizations.'
}

PROCESS = [
    ('Discover', 'Understand the environment', 'Clarify objectives, stakeholders, constraints, assets, and authorization.'),
    ('Assess', 'Evaluate the exposure', 'Apply the approved methods and collect proportionate, defensible evidence.'),
    ('Prioritize', 'Connect findings to impact', 'Consider severity, exploitability, business context, urgency, and effort.'),
    ('Remediate', 'Build a practical roadmap', 'Translate findings into owned, sequenced, and measurable actions.'),
    ('Validate', 'Confirm improvement', 'Where included, retest eligible findings and document remaining risk.'),
]

SERVICES = [
{
'slug':'penetration-testing','title':'Penetration Testing','kicker':'Validate realistic attack paths','headline':'See how far a controlled attack could go—before a real one begins.','summary':'PDDG conducts scoped, authorized testing to validate exploitable weaknesses and show how individual gaps may combine into meaningful business risk.','audience':'Organizations that need evidence of exploitability, validation beyond automated scanning, or a deeper test of existing controls.','triggers':['A major infrastructure or application change','A customer or contractual testing requirement','Concern about attack paths across connected systems','The need to validate prior vulnerability findings'],'scope':['External or internal systems approved during scoping','Authentication and access-control paths','Network segmentation and exposed services','Evidence collection designed to minimize operational impact'],'deliverables':['Executive summary for decision-makers','Validated findings with technical evidence','Business-impact and likelihood context','Prioritized remediation guidance and, where scoped, retesting'],'value':['Separate theoretical weaknesses from demonstrated exposure','Focus remediation on credible attack paths','Give technical teams reproducible evidence'],'frameworks':['NIST guidance','OWASP testing principles','PTES-aligned concepts','Applicable contractual requirements'],'faqs':[('Can penetration testing disrupt systems?','Testing is planned to reduce unnecessary operational risk, but no active test is entirely risk-free. Rules of engagement, exclusions, escalation paths, and testing windows are confirmed before work begins.'),('Is retesting included?','Retesting may be included depending on the agreed scope. The proposal should state the retest window, eligible findings, and reporting method.'),('What is the difference between a scan and a penetration test?','A scan identifies potential weaknesses. A penetration test adds human validation and controlled exploitation to understand whether and how those weaknesses can be used.')]
},
{
'slug':'vulnerability-assessment','title':'Vulnerability Assessment','kicker':'Build a prioritized exposure baseline','headline':'Turn a broad list of weaknesses into a risk-informed starting point.','summary':'A vulnerability assessment identifies and prioritizes weaknesses across approved assets, helping teams understand exposure without assuming every finding carries equal business risk.','audience':'Teams seeking a broad security baseline, pre-audit preparation, or a structured view of weaknesses across systems and infrastructure.','triggers':['No recent assessment baseline','Rapid asset or cloud growth','Audit or customer due-diligence preparation','A backlog with unclear remediation order'],'scope':['Approved hosts, services, platforms, and cloud assets','Configuration and patch exposure','Validation of selected higher-risk findings','Asset-context and ownership mapping where available'],'deliverables':['Asset-level findings','Severity and business-context prioritization','Technical evidence and affected components','Practical remediation sequence'],'value':['Establish a defensible exposure baseline','Reduce noise from raw scanner output','Align owners around the next actions'],'frameworks':['NIST Cybersecurity Framework','CIS Controls','CVSS as one input to prioritization','Relevant regulatory expectations'],'faqs':[('Does an assessment prove vulnerabilities are exploitable?','Not always. Validation depth depends on scope. Penetration testing is generally the better fit when controlled exploitation and attack-path validation are primary objectives.'),('How often should assessments occur?','Frequency depends on change rate, risk, contractual obligations, and the organization’s control environment. Many teams combine periodic assessments with ongoing vulnerability management.'),('Can cloud assets be included?','Cloud assets may be included when ownership, provider requirements, permissions, and the exact test boundaries are confirmed during scoping.')]
},
{
'slug':'vulnerability-management','title':'Vulnerability Management','kicker':'Reduce exposure over time','headline':'Move from periodic findings to a repeatable risk-reduction rhythm.','summary':'Vulnerability management helps organizations track, prioritize, assign, and verify remediation over time instead of treating each assessment as an isolated event.','audience':'Organizations with recurring scans, multiple asset owners, growing remediation backlogs, or a need to demonstrate continuous progress.','triggers':['Findings repeatedly reopen or age past target dates','Ownership is unclear across teams','Scanning exists but risk reduction is difficult to show','Leadership needs consistent exposure reporting'],'scope':['Asset and owner context','Finding normalization and prioritization','Remediation workflow and exception handling','Progress reporting and validation cadence'],'deliverables':['Prioritized remediation register','Ownership and target-date model','Trend and aging views','Validation or retesting recommendations'],'value':['Create accountability without losing technical context','Direct capacity toward the most consequential exposure','Communicate measurable progress'],'frameworks':['NIST Cybersecurity Framework','CIS Controls','Risk-based service-level targets','Applicable governance requirements'],'faqs':[('Is vulnerability management a one-time assessment?','No. It is an operating process that connects discovery, prioritization, ownership, remediation, exception handling, and validation.'),('Can PDDG work with existing tools?','The engagement may incorporate existing scanners, ticketing workflows, and reporting sources when access and integration requirements are agreed during scoping.'),('How are priorities set?','Technical severity is considered alongside exploitability, asset importance, exposure, compensating controls, operational impact, and remediation effort.')]
},
{
'slug':'web-application-security-assessment','title':'Web Application Security Assessment','kicker':'Test the logic behind the interface','headline':'Identify application weaknesses that scanners and happy-path testing can miss.','summary':'PDDG evaluates approved web applications for security weaknesses across authentication, authorization, input handling, business logic, configuration, and session behavior.','audience':'Organizations preparing a release, handling sensitive data, responding to customer assurance requests, or reviewing a high-value application.','triggers':['A new application or major release','Sensitive workflows or customer data','Changes to identity, APIs, or payment flows','A contractual application-testing requirement'],'scope':['Authentication and session behavior','Authorization and role boundaries','Input handling and server-side validation','Business-logic and configuration risks'],'deliverables':['Reproducible application findings','Technical evidence and affected flows','Impact explanation for product and business owners','Prioritized developer-ready recommendations'],'value':['Find weaknesses tied to real user flows','Give developers specific remediation direction','Support safer release decisions'],'frameworks':['OWASP Web Security Testing Guide','OWASP Top 10','OWASP ASVS concepts','Relevant secure-development requirements'],'faqs':[('Do you need test accounts?','Authenticated testing commonly requires dedicated accounts for relevant roles. Exact access, data handling, and environment requirements are confirmed before testing.'),('Can APIs be assessed?','API endpoints may be included when they are explicitly listed in scope and the necessary documentation, authentication, and test data are available.'),('Should testing occur in production?','The right environment depends on realism, data sensitivity, operational tolerance, and test objectives. The decision is made during scoping with clear safeguards.')]
},
{
'slug':'threat-intelligence-and-monitoring','title':'Threat Intelligence and Monitoring','kicker':'Connect external signals to business risk','headline':'Focus attention on emerging threats that are relevant to your organization.','summary':'PDDG helps teams monitor agreed external risk signals, interpret their relevance, and prioritize action with context rather than forwarding undifferentiated alerts.','audience':'Organizations seeking ongoing visibility into exposed data, domain risk, credential exposure, or changing threat conditions.','triggers':['Executives need clearer external-risk visibility','Potential credential or brand exposure','A changing threat landscape for the sector','Limited capacity to analyze raw threat feeds'],'scope':['Approved domains, brands, and external indicators','Credential and exposed-data signals where lawful and appropriate','Threat relevance and risk scoring','Escalation and reporting expectations'],'deliverables':['Contextual alerts','Risk-scored observations','Periodic executive and technical reporting','Recommended response and hardening actions'],'value':['Reduce time spent on irrelevant signals','Identify external exposure earlier','Connect intelligence to accountable action'],'frameworks':['NIST Cybersecurity Framework','MITRE ATT&CK as an analysis reference','Organization-specific risk criteria','Applicable data-handling requirements'],'faqs':[('Is this an incident-response service?','Not by default. Monitoring and intelligence may identify signals that require investigation, but incident-response availability and scope must be established separately.'),('What is monitored?','The monitored sources, identifiers, alert thresholds, and reporting cadence depend on the agreed service scope.'),('Does every alert require immediate action?','No. Alerts should be evaluated for credibility, relevance, affected assets, and business impact before response is prioritized.')]
},
{
'slug':'security-awareness-training','title':'Security Awareness Training','kicker':'Make secure judgment part of daily work','headline':'Prepare people to recognize risk in the moments that matter.','summary':'PDDG develops role-aware training that helps employees identify phishing, social engineering, unsafe data handling, and other behaviors relevant to their work.','audience':'Organizations strengthening security culture, responding to audit requirements, onboarding new staff, or addressing recurring human-risk patterns.','triggers':['Phishing or account-compromise concerns','New or seasonal workforce onboarding','Policy changes that employees must understand','Training completion without visible behavior change'],'scope':['Role and risk discovery','Phishing and social-engineering awareness','Password, device, and data-handling practices','Safe simulations or knowledge checks where included'],'deliverables':['Tailored learning content','Facilitated sessions or approved delivery format','Participation and knowledge observations','Improvement recommendations'],'value':['Make guidance relevant to real roles','Reinforce reporting and escalation habits','Support evidence of an active awareness program'],'frameworks':['NIST awareness guidance','CIS Controls','Organization policy requirements','Applicable sector expectations'],'faqs':[('Can training be customized by role?','Yes, where included in scope. Executives, administrators, finance teams, frontline staff, and general users often face different decisions and threat patterns.'),('Are phishing simulations always included?','No. Simulations are included only when agreed, authorized, and designed with appropriate communication, safety, and measurement controls.'),('Does completion prove employees are secure?','No single training event removes human risk. Effective programs reinforce expectations, measure trends, and improve reporting behavior over time.')]
},
{
'slug':'physical-security-assessment','title':'Physical Security Assessment','kicker':'Evaluate where physical access meets digital risk','headline':'Find on-site weaknesses that can bypass otherwise strong technical controls.','summary':'PDDG reviews approved facilities, access practices, and physical-control dependencies to identify gaps that may affect people, systems, data, and operational continuity.','audience':'Organizations with sensitive facilities, public-facing environments, shared buildings, high-value assets, or regulatory physical-security expectations.','triggers':['A new facility or material layout change','Shared access or visitor-management concerns','Sensitive equipment outside controlled areas','A need to connect physical and cyber risk'],'scope':['Perimeter and entry controls','Visitor, badge, and key practices','Sensitive-area and equipment protection','Physical-to-digital attack paths approved for review'],'deliverables':['Observed control gaps','Risk pathways and affected assets','Photographic evidence only where authorized','Prioritized procedural and physical recommendations'],'value':['Understand security as a connected system','Reduce opportunities for unauthorized access','Support operational and compliance planning'],'frameworks':['NIST physical protection concepts','CPTED principles where relevant','Organization access-control policies','Applicable facility requirements'],'faqs':[('Does this include covert entry testing?','Only if explicitly authorized and carefully scoped. Many engagements are observational and procedural assessments without attempted bypass.'),('Will photographs be taken?','Evidence practices are agreed in advance. Photography may be restricted or excluded depending on the facility and data-handling requirements.'),('Can multiple sites be reviewed?','Yes, but each facility’s location, operating constraints, access process, and sampling approach must be reflected in scope.')]
},
{
'slug':'cybersecurity-policy-assessment','title':'Cybersecurity Policy Assessment','kicker':'Align written expectations with operational reality','headline':'Identify the policy gaps that create unclear ownership and inconsistent security decisions.','summary':'PDDG evaluates approved cybersecurity policies, processes, and procedures for clarity, coverage, alignment, and practical use across the organization.','audience':'Organizations preparing for audits, formalizing governance, updating outdated documents, or resolving gaps between policy and practice.','triggers':['Policies have not kept pace with technology or roles','Audit findings cite documentation or governance gaps','Security ownership and exceptions are unclear','Multiple documents conflict or duplicate requirements'],'scope':['Policy inventory and hierarchy','Roles, approvals, and exception handling','Alignment to selected frameworks or obligations','Operational evidence and stakeholder interviews where included'],'deliverables':['Gap and overlap analysis','Prioritized policy recommendations','Ownership and review-cycle guidance','Roadmap for document updates'],'value':['Clarify accountable decisions','Reduce policy-practice disconnects','Support more consistent audit readiness'],'frameworks':['NIST Cybersecurity Framework','CIS Controls','ISO/IEC 27001 concepts','Selected regulatory or contractual criteria'],'faqs':[('Does a policy review guarantee compliance?','No. A policy assessment can identify alignment gaps and improvement priorities, but compliance depends on the applicable requirements, implemented controls, evidence, and legal interpretation.'),('Will PDDG rewrite every policy?','Document development or revision may be included separately. The assessment scope should distinguish review, recommendations, drafting, and implementation support.'),('Are interviews part of the review?','Stakeholder interviews may be useful to understand how written requirements operate in practice and are included when agreed during scoping.')]
},
{
'slug':'wireless-bluetooth-security-audit','title':'Wireless and Bluetooth Security Audit','kicker':'Map the signals that extend beyond the wall','headline':'Understand wireless exposure across networks, devices, and physical space.','summary':'PDDG reviews approved wireless and Bluetooth environments to identify configuration, segmentation, coverage, device, and access weaknesses that may create unintended entry paths.','audience':'Organizations with guest networks, distributed access points, connected devices, public facilities, or uncertainty about wireless assets.','triggers':['A new site or wireless redesign','Unmanaged or unknown access-point concerns','Guest and internal network separation questions','Bluetooth-enabled operational or customer devices'],'scope':['Authorized Wi-Fi networks and access points','Encryption, authentication, and segmentation','Rogue or unexpected signal review','Approved Bluetooth services and device exposure'],'deliverables':['Wireless asset and signal observations','Configuration and segmentation findings','Location-aware evidence where authorized','Prioritized hardening recommendations'],'value':['Reveal exposure that wired inventories miss','Validate guest and internal separation','Connect radio-frequency risk to facility controls'],'frameworks':['NIST wireless guidance','CIS Controls','Vendor hardening guidance','Organization network policies'],'faqs':[('Will you attempt to connect to every network?','No. Testing actions are limited to explicitly authorized networks, devices, methods, locations, and time windows.'),('Can guest Wi-Fi be assessed separately?','Yes. Guest access, segmentation, captive portals, and paths toward internal resources can be evaluated within an approved scope.'),('Does the audit include Bluetooth devices?','Bluetooth review is included only for approved devices and services, with safety and operational constraints agreed in advance.')]
},
]

SERVICE_MAP = {s['slug']: s for s in SERVICES}

INDUSTRIES = [
{'slug':'healthcare','title':'Healthcare','headline':'Protect clinical continuity while strengthening safeguards around health information.','summary':'Healthcare environments connect protected health information, clinical workflows, medical devices, third parties, and time-sensitive operations. Assessment scope must respect patient care and operational constraints.','pressures':['HIPAA-related safeguards and evidence','Ransomware resilience and clinical availability','Medical-device and legacy-system constraints','Third-party and vendor access'],'decision':['CISO and security leadership','CIO and IT operations','Privacy and compliance leaders','Clinical engineering and risk management'],'surfaces':['Identity and remote access','Clinical and administrative applications','Medical and connected devices','Facilities, wireless networks, and vendors'],'services':['vulnerability-assessment','penetration-testing','cybersecurity-policy-assessment','security-awareness-training'],'considerations':['Patient care takes priority over test convenience','Protected data should be minimized in evidence','Testing windows and escalation paths require clinical coordination','HIPAA alignment does not equal guaranteed compliance'],'value':['Prioritized exposure across clinical and business systems','Clearer remediation ownership','Reporting that supports technical and compliance discussions']},
{'slug':'financial-services','title':'Financial Services','headline':'Assess the controls behind customer trust, transactions, and connected financial operations.','summary':'Financial organizations manage sensitive customer information, fraud exposure, complex access models, vendors, and exacting regulatory or contractual expectations.','pressures':['Customer financial-information protection','Fraud and account-takeover exposure','Third-party and cloud dependencies','Regulatory and contractual scrutiny'],'decision':['CISO and security operations','CIO and technology leadership','Risk, compliance, and audit teams','Fraud and identity leaders'],'surfaces':['Customer portals and APIs','Identity, privileged access, and payments','Cloud and vendor connections','Employee workflows and facilities'],'services':['web-application-security-assessment','penetration-testing','threat-intelligence-and-monitoring','cybersecurity-policy-assessment'],'considerations':['Production transaction paths require conservative safeguards','Test data and evidence handling must be defined','Third-party boundaries may constrain coverage','Assessment supports readiness but does not guarantee compliance'],'value':['Evidence tied to realistic financial workflows','Clearer visibility across technical and human controls','Priorities leadership can connect to operational risk']},
{'slug':'government','title':'Government','headline':'Support mission continuity with assessments shaped around public-sector constraints.','summary':'Government and contractor environments balance sensitive systems, procurement requirements, data classification, operational continuity, and NIST-aligned control expectations.','pressures':['Sensitive public-sector systems and information','Procurement and authorization requirements','Contractor and shared-responsibility environments','Continuity of public services'],'decision':['CISO and security program leaders','CIO and infrastructure teams','Authorizing and compliance officials','Program and contract leadership'],'surfaces':['Public-facing systems','Identity and administrative access','Contractor and partner connections','Facilities and wireless infrastructure'],'services':['penetration-testing','vulnerability-management','physical-security-assessment','cybersecurity-policy-assessment'],'considerations':['Authorization and rules of engagement are foundational','Data classification affects evidence handling','Tooling and personnel requirements may be contract-specific','NIST alignment is scoped to selected controls and evidence'],'value':['Mission-aware remediation priorities','Technical evidence framed for governance decisions','A clearer path from findings to accountable action']},
{'slug':'education','title':'Education','headline':'Strengthen open, distributed learning environments without losing operational practicality.','summary':'Education combines student and employee information, open networks, distributed devices, research systems, seasonal users, and often-limited internal security capacity.','pressures':['Student and employee information','Phishing and account compromise','Open networks and unmanaged devices','Research data and decentralized technology'],'decision':['CIO and IT directors','Security and infrastructure teams','Privacy, legal, and risk leaders','Academic and administrative technology owners'],'surfaces':['Identity and email','Learning and administrative platforms','Labs, research, and endpoint fleets','Campus wireless and physical access'],'services':['security-awareness-training','wireless-bluetooth-security-audit','vulnerability-assessment','cybersecurity-policy-assessment'],'considerations':['Academic calendars affect testing windows','Decentralized ownership requires careful discovery','Open-access goals must be balanced with segmentation','Evidence collection should minimize student data'],'value':['Practical priorities for constrained teams','Better visibility across decentralized assets','Clearer guidance for staff, faculty, and leadership']},
{'slug':'manufacturing','title':'Manufacturing','headline':'Evaluate cyber exposure without losing sight of safety, uptime, and operational technology.','summary':'Manufacturing environments connect enterprise IT, industrial systems, remote access, vendors, production facilities, and operational processes where availability and safety matter.','pressures':['Production uptime and safety','Legacy and specialized operational systems','Vendor and remote-access dependencies','IT and operational technology convergence'],'decision':['CISO and security leadership','CIO and IT operations','Plant and operations leaders','Engineering, safety, and risk teams'],'surfaces':['Remote access and identity','Industrial and production networks','Enterprise applications and cloud systems','Facilities, wireless, and vendor connections'],'services':['vulnerability-assessment','penetration-testing','wireless-bluetooth-security-audit','physical-security-assessment'],'considerations':['Safety and uptime constrain active testing','Operational technology requires specialized scoping','Vendor ownership can limit access and evidence','Production changes need coordinated escalation paths'],'value':['Exposure priorities tied to operational impact','Clearer visibility across IT and OT dependencies','Practical remediation sequencing for production environments']},
{'slug':'hospitality','title':'Hospitality','headline':'Protect guest trust across connected properties, payment systems, people, and physical spaces.','summary':'Hospitality environments combine guest information, payments, public networks, property systems, seasonal workforces, vendors, and always-on operations.','pressures':['Guest information and payment security','Distributed properties and vendor access','Public wireless and connected devices','High staff turnover and social-engineering exposure'],'decision':['CIO and technology leadership','Security and risk teams','Property and operations leaders','Finance, privacy, and guest-services leaders'],'surfaces':['Reservations, payments, and guest applications','Identity and employee workflows','Guest and operational wireless networks','Facilities, devices, and third parties'],'services':['web-application-security-assessment','wireless-bluetooth-security-audit','security-awareness-training','physical-security-assessment'],'considerations':['Guest operations require careful test windows','Property systems and vendors create shared boundaries','Evidence must minimize guest and payment data','Physical and digital controls should be reviewed together'],'value':['Practical priorities across distributed properties','Clearer visibility into guest-facing exposure','Recommendations that reflect operational realities']},
]

RESOURCES = [
{'slug':'penetration-testing-vs-vulnerability-assessment','type':'Guide','title':'Penetration Testing vs. Vulnerability Assessment','summary':'Understand the difference between broad weakness discovery and controlled validation of realistic attack paths.','sections':[('The essential distinction','A vulnerability assessment identifies and prioritizes potential weaknesses across approved assets. A penetration test adds human validation and controlled exploitation to determine whether and how selected weaknesses can be used.'),('Choose based on the decision','Use a vulnerability assessment when you need a broad baseline, audit preparation, or an ordered view of exposure. Use penetration testing when you need evidence of exploitability, attack-path validation, or deeper assurance around important systems.'),('They often work together','A mature program may use recurring vulnerability assessment to maintain visibility and targeted penetration testing to validate higher-risk systems or major changes.') ]},
{'slug':'what-a-cybersecurity-assessment-report-should-include','type':'Report guide','title':'What a Cybersecurity Assessment Report Should Include','summary':'Use this guide to evaluate whether a report can support both technical remediation and leadership decisions.','sections':[('Executive context','A useful report explains why the assessment occurred, what was in scope, the material themes, and the decisions leadership should consider.'),('Technical evidence','Findings should identify affected assets, conditions, evidence, impact, and enough detail for responsible teams to reproduce and remediate the issue.'),('Prioritization and ownership','Technical severity alone is not enough. Reports should consider exploitability, business impact, exposure, compensating controls, urgency, effort, ownership, and validation expectations.'),('Limitations and remaining risk','A credible report states assumptions, exclusions, testing constraints, evidence-handling boundaries, and what the assessment does not prove.') ]},
{'slug':'prioritizing-cybersecurity-findings-by-business-risk','type':'Decision brief','title':'Prioritizing Cybersecurity Findings by Business Risk','summary':'Move beyond a severity-only list by connecting technical evidence to exploitability, operational context, ownership, and urgency.','sections':[('Severity is one input','A high technical score does not automatically mean the highest business priority. Asset importance, exposure, realistic attack paths, compensating controls, and operational consequences change the decision.'),('Use a consistent model','Consider technical severity, likelihood and exploitability, business impact, affected data and operations, exposure, remediation effort, dependencies, and accountable ownership.'),('Make the output actionable','The final priority should support a clear next action, named owner, target timing, exception path, and validation method.') ]},
{'slug':'security-assessment-readiness-checklist','type':'Checklist','title':'Security Assessment Readiness Checklist','summary':'Prepare the objectives, stakeholders, assets, authorization, safeguards, and evidence expectations needed for a practical assessment.','checklist':['Define the business decision the assessment must support','Identify executive, technical, legal, compliance, and operational stakeholders','Document approved assets, applications, facilities, identities, and locations','Confirm ownership and written authorization','List exclusions and prohibited testing methods','Set testing windows and operational constraints','Establish emergency stop conditions and escalation contacts','Prepare test accounts and representative roles where needed','Define evidence minimization, storage, transfer, and retention expectations','Identify third-party and cloud-provider requirements','Agree on reporting audiences and desired deliverables','Clarify remediation ownership and retesting expectations']},
{'slug':'common-wireless-security-weaknesses','type':'Field guide','title':'Common Wireless Security Weaknesses','summary':'Review the wireless and Bluetooth conditions that can create unintended paths into facilities, devices, and networks.','sections':[('Unknown or unmanaged signals','Rogue access points, personal hotspots, legacy devices, and incomplete inventories can create exposure outside normal wired-asset processes.'),('Weak separation','Guest, operational, and internal networks need deliberate segmentation, authentication, and monitoring. A separate name alone does not prove isolation.'),('Configuration and lifecycle gaps','Legacy encryption, shared credentials, default settings, outdated firmware, excessive coverage, and unsupported devices can undermine stronger controls.'),('Physical context matters','Wireless exposure extends through space. Coverage, facility boundaries, nearby tenants, public areas, and device locations can change the risk.') ]},
{'slug':'building-an-effective-security-awareness-program','type':'Program guide','title':'Building an Effective Security Awareness Program','summary':'Create role-aware training that reinforces secure decisions instead of treating annual completion as the final objective.','sections':[('Start with real decisions','Training should reflect the messages, systems, data, vendors, and escalation decisions people actually encounter.'),('Adapt by role','Executives, administrators, finance teams, frontline staff, technical teams, and general users face different threat patterns and responsibilities.'),('Reinforce over time','Effective programs combine clear expectations, concise learning, safe exercises where appropriate, reporting habits, follow-up communication, and trend measurement.'),('Measure more than completion','Participation matters, but reporting behavior, repeat patterns, knowledge observations, and operational feedback provide stronger evidence of improvement.') ]},
]

ICONS = {
'default': '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3l7 3v5c0 4.8-2.9 8-7 10-4.1-2-7-5.2-7-10V6l7-3Z"/><path d="m9 12 2 2 4-5"/></svg>',
'penetration-testing':'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 2v4M12 18v4M2 12h4M18 12h4"/></svg>',
'vulnerability-assessment':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3l7 3v5c0 4.8-2.9 8-7 10-4.1-2-7-5.2-7-10V6l7-3Z"/><path d="M8.5 12h7M12 8.5v7"/></svg>',
'vulnerability-management':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h11a5 5 0 0 1 0 10H8"/><path d="m8 13-4 4 4 4M20 7l-4-4"/></svg>',
'web-application-security-assessment':'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M8 14l-2 2 2 2M16 14l2 2-2 2"/></svg>',
'threat-intelligence-and-monitoring':'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 3 15 0 18M12 3c-3 3-3 15 0 18"/></svg>',
'security-awareness-training':'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="8" r="3"/><path d="M3 20c.4-4 2.4-6 6-6s5.6 2 6 6M17 7h4M19 5v4"/></svg>',
'physical-security-assessment':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 21V5l8-3 8 3v16M9 21v-5h6v5M8 8h1M15 8h1M8 12h1M15 12h1"/></svg>',
'cybersecurity-policy-assessment':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3h9l3 3v15H6z"/><path d="M15 3v4h4M9 11h6M9 15h6"/></svg>',
'wireless-bluetooth-security-audit':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 9a12 12 0 0 1 16 0M7 13a8 8 0 0 1 10 0M10 17a3 3 0 0 1 4 0"/><circle cx="12" cy="20" r="1"/></svg>',
}
ARROW = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 17 17 7M8 7h9v9" fill="none" stroke="currentColor" stroke-width="1.7"/></svg>'


def depth_prefix(route: str) -> str:
    if not route:
        return ''
    return '../' * len([p for p in route.strip('/').split('/') if p])

def href(prefix, route=''):
    if route == '': return prefix + 'index.html'
    return prefix + route.strip('/') + '/index.html'

def asset(prefix, path): return prefix + 'assets/' + path

def section_head(label, title, text=''):
    return f'''<div class="section-head reveal"><div><span class="eyebrow">{escape(label)}</span><h2>{title}</h2></div>{f'<p>{escape(text)}</p>' if text else ''}</div>'''

def button(label, url, outline=False, small=False):
    c = 'btn' + (' btn-outline' if outline else '') + (' btn-sm' if small else '')
    return f'<a class="{c}" href="{url}">{escape(label)} {ARROW}</a>'

def list_html(items, cls='check-list'):
    return '<ul class="%s">%s</ul>' % (cls, ''.join(f'<li>{escape(x)}</li>' for x in items))

def process_html():
    steps=''.join(f'''<article class="process-step reveal"><div class="step-dot">{i:02}</div><h3>{escape(name)}</h3><p><strong style="color:#dce8ec">{escape(sub)}</strong><br>{escape(desc)}</p></article>''' for i,(name,sub,desc) in enumerate(PROCESS,1))
    return f'''<div class="process-wrap" data-process><div class="process-line"><div class="process-line-fill" data-process-fill></div></div><div class="process-grid">{steps}</div></div>'''

def signal_board(prefix, label='Assessment core'):
    return f'''<div class="signal-board reveal" data-tilt><div class="signal-top"><span>{escape(label)}</span><span class="live"><i class="status-dot"></i> system active</span></div><div class="signal-map"><canvas class="network-canvas" data-network aria-label="Animated network risk visualization"></canvas></div><div class="signal-stats"><div class="signal-stat"><small>Risk signal</small><strong>Contextual</strong></div><div class="signal-stat"><small>Decision output</small><strong>Prioritized</strong></div><div class="signal-stat"><small>Evidence</small><strong>Defensible</strong></div></div></div>'''

def orbit_visual():
    labs=['External exposure','Application security','Human risk','Physical + wireless']
    return f'''<div class="ai-orbit reveal" data-tilt><canvas class="network-canvas" data-network aria-label="Animated cybersecurity intelligence network"></canvas><div class="scan-line"></div><div class="orbit-core"><div><strong>PDDG</strong><small>Risk intelligence</small></div></div>{''.join(f'<div class="orbit-label"><i></i>{x}</div>' for x in labs)}</div>'''

def breadcrumb(prefix, parts):
    rendered=[]
    for label,route in parts:
        rendered.append(f'<a href="{href(prefix,route)}">{escape(label)}</a>' if route is not None else escape(label))
    return '<div class="breadcrumb">' + ' / '.join(rendered) + '</div>'

def hero(prefix, eyebrow, title, summary, buttons=None, inner=True, crumbs=None, visual='board'):
    buttons = buttons or []
    bc = breadcrumb(prefix, crumbs) if crumbs else ''
    vis = orbit_visual() if visual=='orbit' else signal_board(prefix)
    return f'''<section class="hero {'inner-hero' if inner else ''}"><div class="container hero-grid"><div class="hero-copy reveal">{bc}<span class="eyebrow">{escape(eyebrow)}</span><h1>{title}</h1><p class="lede">{escape(summary)}</p>{f'<div class="button-row">{"".join(buttons)}</div>' if buttons else ''}<div class="hero-meta"><span><i></i>Authorized scope</span><span><i></i>Risk-driven</span><span><i></i>Actionable reporting</span></div></div>{vis}</div></section>'''

def service_card(prefix, s, i, compact=False):
    return f'''<article class="card service-card reveal"><div class="card-pad"><div class="card-number"><span>{i:02}</span><div class="icon-box">{ICONS.get(s['slug'], ICONS['default'])}</div></div><h3>{escape(s['title'])}</h3><p>{escape(s['summary'])}</p><a class="card-link" href="{href(prefix,'services/'+s['slug'])}">View service <span>↗</span></a></div><div class="service-line"></div></article>'''

def credentials(prefix):
    imgs=''.join(f'<div class="credential"><img src="{asset(prefix,f"images/cert-{i}.png")}" alt="Professional cybersecurity credential badge" loading="lazy"></div>' for i in range(2,10))
    return f'<div class="credentials"><div class="credential-track">{imgs}{imgs}</div></div>'

def faq_html(items):
    out=[]
    for i,(q,a) in enumerate(items):
        out.append(f'''<div class="faq-item"><button class="faq-question" data-faq aria-expanded="{'true' if i==0 else 'false'}"><span>{escape(q)}</span><span class="faq-icon">+</span></button><div class="faq-answer"><div><p>{escape(a)}</p></div></div></div>''')
    return '<div class="faq-list">'+''.join(out)+'</div>'

def cta(prefix, title='Start with a clearer view of your security risk.', text='Discuss your concerns, identify an appropriate assessment path, and determine what is required to develop a practical scope.'):
    return f'''<section class="section section-tight"><div class="container"><div class="cta-panel reveal"><div class="cta-content"><div><span class="eyebrow">A clearer next step</span><h2>{escape(title)}</h2><p>{escape(text)}</p></div>{button('Book a Security Fit Call',href(prefix,'book-a-security-fit-call'))}</div></div></div></section>'''

def nav(prefix, active):
    entries=[('Home',''),('Services','services'),('Industries','industries'),('Approach','approach'),('Resources','resources'),('About','about'),('Contact','contact')]
    return ''.join(f'<a class="{"active" if active==r or (r=="" and active=="home") else ""}" href="{href(prefix,r)}">{label}</a>' for label,r in entries) + button('Book a Call', href(prefix,'book-a-security-fit-call'), small=True)

def footer(prefix):
    return f'''<footer class="footer"><div class="container"><div class="footer-main"><div class="footer-brand"><img src="{asset(prefix,'images/pddg-logo.png')}" alt="Pinnacle Digital Defense Group"><p>{escape(COMPANY['tagline'])}</p><div class="footer-contact"><a href="tel:+13015321463">{COMPANY['phone']}</a><a href="mailto:{COMPANY['email']}">{COMPANY['email']}</a><span>{COMPANY['address']}</span><span>{COMPANY['hours']}</span></div></div><div><h4>Company</h4><div class="footer-links"><a href="{href(prefix,'about')}">About PDDG</a><a href="{href(prefix,'approach')}">Our Approach</a><a href="{href(prefix,'resources')}">Resources</a><a href="{href(prefix,'case-studies')}">Case Studies</a><a href="{href(prefix,'frequently-asked-questions')}">FAQs</a></div></div><div><h4>Services</h4><div class="footer-links">{''.join(f'<a href="{href(prefix,"services/"+s["slug"])}">{escape(s["title"])}</a>' for s in SERVICES[:6])}</div></div><div><h4>Industries</h4><div class="footer-links">{''.join(f'<a href="{href(prefix,"industries/"+x["slug"])}">{escape(x["title"])}</a>' for x in INDUSTRIES)}</div></div></div><div class="footer-bottom"><span>© 2026 Pinnacle Digital Defense Group. All rights reserved.</span><div class="footer-legal"><a href="{href(prefix,'privacy-policy')}">Privacy Policy</a><a href="{href(prefix,'terms-and-conditions')}">Terms & Conditions</a><a href="{href(prefix,'accessibility-statement')}">Accessibility</a></div></div></div></footer>'''

def page(route, title, description, body, active='home', extra_head=''):
    prefix=depth_prefix(route)
    canonical = BASE + ('/' + route.strip('/') + '/' if route else '/')
    html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | PDDG</title><meta name="description" content="{escape(description)}"><link rel="canonical" href="{canonical}"><meta property="og:type" content="website"><meta property="og:title" content="{escape(title)} | PDDG"><meta property="og:description" content="{escape(description)}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{BASE}/assets/images/pddg-logo.png"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#02070d"><link rel="icon" href="{asset(prefix,'images/favicon.svg')}" type="image/svg+xml"><link rel="manifest" href="{prefix}site.webmanifest"><link rel="stylesheet" href="{asset(prefix,'css/styles.css')}">{extra_head}</head><body><a class="skip-link" href="#main">Skip to main content</a><div class="topbar"><div class="container topbar-inner"><span><i class="status-dot"></i>Risk-driven cybersecurity assessments for regulated and operationally sensitive organizations.</span><span>Columbia, Maryland · {COMPANY['phone']}</span></div></div><header class="site-header"><div class="container header-inner"><a class="logo" href="{href(prefix,'')}" aria-label="PDDG home"><img src="{asset(prefix,'images/pddg-logo.png')}" alt="Pinnacle Digital Defense Group"></a><button class="menu-toggle" aria-label="Open navigation" aria-expanded="false"><span></span></button><nav class="nav" aria-label="Main navigation">{nav(prefix,active)}</nav></div></header><main id="main">{body}</main>{footer(prefix)}<script src="{asset(prefix,'js/main.js')}" defer></script></body></html>'''
    path = ROOT / ('index.html' if not route else route.strip('/') + '/index.html')
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding='utf-8')

def detail_cards(items):
    return '<div class="detail-cards">'+''.join(f'<article class="detail-card reveal"><span class="num">{i:02}</span><h3>{escape(x)}</h3></article>' for i,x in enumerate(items,1))+'</div>'

def home_page():
    prefix=''
    hero_html=hero(prefix,'Independent · Risk-driven · Actionable','Know where your organization is <span class="text-gradient">exposed</span>—and what to fix first.',COMPANY['tagline'],[button('Book a Security Fit Call',href(prefix,'book-a-security-fit-call')),button('Explore Services',href(prefix,'services'),True)],inner=False,visual='orbit')
    mar_items=['Digital systems & applications','Human awareness & procedures','Physical facilities & wireless','Executive risk communication']*2
    marquee='<div class="marquee"><div class="marquee-track">'+''.join(f'<div class="marquee-item">{x}</div>' for x in mar_items)+'</div></div>'
    challenge=f'''<section class="section section-border"><div class="container">{section_head('The challenge','Cybersecurity decisions rarely fail because teams lack findings.','They fail when technical findings are disconnected from business context, accountable ownership, operational constraints, and clear next actions.')}<div class="challenge-list"><article class="challenge reveal"><span class="num">01</span><h3>What can realistically be exploited?</h3><p>Separate theoretical weaknesses from credible attack paths.</p></article><article class="challenge reveal"><span class="num">02</span><h3>What creates the most meaningful risk?</h3><p>Connect evidence to assets, data, operations, and mission impact.</p></article><article class="challenge reveal"><span class="num">03</span><h3>What should happen next?</h3><p>Translate findings into prioritized, owned, and measurable action.</p></article></div></div></section>'''
    outcomes=f'''<section class="section section-dark"><div class="container">{section_head('What clients need','Evidence that supports action—not another undifferentiated list.','PDDG connects technical evidence to business relevance, remediation ownership, and a clearer decision path.')}<div class="grid-3"><article class="card card-pad reveal"><div class="icon-box">{ICONS['penetration-testing']}</div><h3 style="margin-top:44px">Validated exposure</h3><p>Understand which weaknesses are credible, how they may connect, and where safeguards matter most.</p></article><article class="card card-pad reveal"><div class="icon-box">{ICONS['vulnerability-management']}</div><h3 style="margin-top:44px">Prioritized action</h3><p>Sequence remediation using technical severity, exploitability, business context, urgency, and effort.</p></article><article class="card card-pad reveal"><div class="icon-box">{ICONS['cybersecurity-policy-assessment']}</div><h3 style="margin-top:44px">Decision-ready reporting</h3><p>Give technical and executive audiences the evidence, context, ownership, and next steps they need.</p></article></div></div></section>'''
    first=SERVICES[0]
    tabs=''.join(f'''<button class="service-tab {'active' if i==1 else ''}" data-index="{i:02}" data-title="{escape(s['title'])}" data-text="{escape(s['summary'])}" data-href="{href(prefix,'services/'+s['slug'])}"><small>{i:02}</small><span>{escape(s['title'])}</span><b>↗</b></button>''' for i,s in enumerate(SERVICES,1))
    services=f'''<section class="section section-border section-glow"><div class="container">{section_head('Security services','Coverage built around the decision you need to make.','Select a service to explore its role, scope, and expected output. Every active test begins with explicit authorization and agreed rules of engagement.')}<div class="service-showcase"><div class="service-tabs">{tabs}</div><div class="service-stage reveal" data-service-stage><div class="stage-content"><span class="stage-index" data-stage-index>01 / Assessment capability</span><h2 data-stage-title>{first['title']}</h2><p data-stage-text>{first['summary']}</p><div class="button-row"><a class="btn btn-outline" data-stage-link href="{href(prefix,'services/'+first['slug'])}">Explore service {ARROW}</a></div></div><div class="stage-orb"></div></div></div></div></section>'''
    method=f'''<section class="section section-dark"><div class="container">{section_head('Our method','A controlled path from uncertainty to accountable action.','The process adapts to the selected service and environment. No active testing begins without an agreed scope and rules of engagement.')}{process_html()}</div></section>'''
    certs=f'''<section class="section-tight section-border"><div class="container"><div class="section-head" style="margin-bottom:35px"><div><span class="eyebrow">Professional credentials</span><h3>Qualified expertise, applied with restraint.</h3></div><p>Credentials support capability. Scope, evidence, limitations, and responsible execution determine whether the work is useful.</p></div>{credentials(prefix)}</div></section>'''
    inds=''.join(f'''<a class="industry-card reveal" href="{href(prefix,'industries/'+x['slug'])}"><span class="eyebrow">{i:02} · Sector</span><h3>{escape(x['title'])}</h3><p>{escape(x['summary'])}</p><span class="card-link">View industry <span>↗</span></span></a>''' for i,x in enumerate(INDUSTRIES,1))
    industries=f'''<section class="section section-border"><div class="container">{section_head('Industries','Security assessment shaped around operational reality.','Regulated and operationally sensitive environments require different safeguards, stakeholders, evidence expectations, and testing constraints.')}<div class="industry-grid">{inds}</div></div></section>'''
    report=f'''<section class="section section-dark"><div class="container">{section_head('Decision-ready output','Reporting designed for technical action and leadership decisions.','The same evidence is framed differently for the people who remediate the issue and the people accountable for risk.')}{report_preview()}</div></section>'''
    resource_cards=''.join(resource_card(prefix,r,i) for i,r in enumerate(RESOURCES[:3],1))
    resources=f'''<section class="section section-border"><div class="container">{section_head('Resources','Use practical guidance before the first scope conversation.','Review assessment choices, reporting expectations, risk prioritization, and readiness requirements.')}<div class="resource-grid">{resource_cards}</div><div class="button-row">{button('View all resources',href(prefix,'resources'),True)}</div></div></section>'''
    faqs=[('What happens during a Security Fit Call?','The conversation focuses on your objective, environment, constraints, stakeholders, and the type of security decision you need to make. It is not an active assessment.'),('Does PDDG guarantee compliance?','No. Assessments can identify gaps and support readiness, but compliance depends on applicable requirements, implemented controls, evidence, legal interpretation, and ongoing operation.'),('How is testing authorized?','Scope, assets, methods, identities, locations, time windows, safeguards, exclusions, stop conditions, and escalation contacts are confirmed before active testing begins.'),('Can services be combined?','Yes. The right combination depends on the decision, risk, environment, authorization, operational constraints, and desired reporting outcome.')]
    faq=f'''<section class="section section-border"><div class="narrow">{section_head('Common questions','Start with the questions that protect the engagement.','Clear scope, authorization, safeguards, evidence expectations, and limitations are part of responsible assessment work.')}{faq_html(faqs)}</div></section>'''
    body=hero_html+marquee+challenge+outcomes+services+method+certs+industries+report+resources+faq+cta(prefix)
    page('', 'Risk-Driven Cybersecurity Assessments', COMPANY['tagline'], body, 'home')

def report_preview():
    return '''<div class="report-preview reveal"><aside class="report-sidebar"><span class="mono">Executive risk overview</span><h3>Exposure translated into action.</h3><div class="risk-bars"><div class="risk-row"><span>Critical</span><div class="risk-bar"><i style="width:28%"></i></div><b>2</b></div><div class="risk-row"><span>High</span><div class="risk-bar"><i style="width:58%"></i></div><b>5</b></div><div class="risk-row"><span>Moderate</span><div class="risk-bar"><i style="width:82%"></i></div><b>9</b></div></div></aside><div class="report-main"><div class="report-tabs"><span>Evidence</span><span>Impact</span><span>Owner</span><span>Action</span><span>Validation</span></div><span class="mono">Illustrative report structure</span><div class="finding"><div class="finding-top">External identity path creates elevated exposure <span>Priority 01</span></div><small>Validated evidence · Business context · Named owner · Sequenced remediation</small></div><div class="finding"><div class="finding-top">Access-control inconsistency across application roles <span>Priority 02</span></div><small>Reproducible flow · Affected users · Developer guidance · Retest criteria</small></div><div class="finding"><div class="finding-top">Guest wireless path lacks expected separation <span>Priority 03</span></div><small>Location-aware evidence · Operational dependency · Hardening sequence</small></div></div></div>'''

def resource_card(prefix,r,i):
    return f'''<article class="card resource-card reveal"><div class="resource-meta"><span>{escape(r['type'])}</span><span>{i:02}</span></div><h3>{escape(r['title'])}</h3><p>{escape(r['summary'])}</p><a class="card-link" href="{href(prefix,'resources/'+r['slug'])}">Read resource <span>↗</span></a></article>'''

def services_hub():
    prefix='../'
    body=hero(prefix,'Security services','Assess exposure. <span class="text-gradient">Strengthen decisions.</span>','PDDG provides risk-driven cybersecurity assessments, clear reporting, and practical remediation guidance across digital, human, physical, and wireless control layers.',[button('Book a Security Fit Call',href(prefix,'book-a-security-fit-call')),button('View Our Approach',href(prefix,'approach'),True)],crumbs=[('Home',''),('Services',None)])
    body+=f'''<section class="section section-border"><div class="container">{section_head('Full capability set','Choose the assessment path that matches the decision.','The exact methodology, assets, test actions, safeguards, and deliverables are confirmed during scoping.')}<div class="grid-3">{''.join(service_card(prefix,s,i) for i,s in enumerate(SERVICES,1))}</div></div></section>'''
    body+=f'''<section class="section section-dark"><div class="container">{section_head('Choose by objective','Start with the problem—not the tool.','A focused objective makes scope, evidence, safeguards, and reporting more useful.')}<div class="split-panel"><div class="split-side reveal"><span class="mono">Assess</span><h3>Understand current exposure.</h3><p>Build a baseline, validate attack paths, review applications, or evaluate wireless and physical dependencies.</p>{list_html(['Broad exposure baseline','Realistic attack-path validation','Application and API review','Facility and wireless review'],'split-list')}</div><div class="split-side reveal"><span class="mono">Strengthen & monitor</span><h3>Reduce risk over time.</h3><p>Improve remediation rhythm, external visibility, employee judgment, and the policies that guide operational decisions.</p>{list_html(['Vulnerability management','Threat intelligence and monitoring','Security awareness training','Cybersecurity policy assessment'],'split-list')}</div></div></div></section>'''
    body+=f'''<section class="section section-border"><div class="container">{section_head('Methodology','Structured, authorized, and grounded in business context.','No active testing begins without an agreed scope and rules of engagement.')}{process_html()}</div></section>'''
    body+=f'''<section class="section-tight section-border"><div class="container">{credentials(prefix)}</div></section>'''+cta(prefix)
    page('services','Cybersecurity Services','Risk-driven cybersecurity assessment services across digital, human, physical, and wireless control layers.',body,'services')

def service_page(s):
    route='services/'+s['slug']; prefix='../../'
    body=hero(prefix,s['kicker'],escape(s['headline']).replace('—','—'),s['summary'],[button('Discuss this service',href(prefix,'book-a-security-fit-call')),button('All services',href(prefix,'services'),True)],crumbs=[('Home',''),('Services','services'),(s['title'],None)])
    body+=f'''<section class="section section-border"><div class="container">{section_head('Who it is for','A focused engagement for a defined security decision.',s['audience'])}<div class="detail-cards">{detail_cards(s['triggers'])[26:-6] if False else ''.join(f'<article class="detail-card reveal"><span class="num">{i:02}</span><h3>{escape(x)}</h3></article>' for i,x in enumerate(s['triggers'],1))}</div></div></section>'''
    body+=f'''<section class="section section-dark"><div class="container">{section_head('Assessment coverage','Coverage shaped around the approved objective.','Testing never extends beyond explicitly authorized systems, facilities, methods, identities, locations, or time windows.')}<div class="split-panel"><div class="split-side reveal"><span class="mono">What may be assessed</span><h3>Approved coverage.</h3>{list_html(s['scope'],'split-list')}</div><div class="split-side reveal"><span class="mono">Expected deliverables</span><h3>Evidence designed to support action.</h3>{list_html(s['deliverables'],'split-list')}</div></div></div></section>'''
    body+=f'''<section class="section section-border"><div class="container">{section_head('Methodology','Structured, authorized, and grounded in business context.','The process adapts to the selected service and environment. No active testing begins without an agreed scope and rules of engagement.')}{process_html()}</div></section>'''
    body+=f'''<section class="section section-dark"><div class="container">{section_head('Business value','Use the findings to make a clearer risk decision.','Specific output varies according to engagement scope and the needs of executive and technical audiences.')}<div class="grid-3">{''.join(f'<article class="card card-pad reveal"><span class="eyebrow">{i:02}</span><h3>{escape(x)}</h3></article>' for i,x in enumerate(s['value'],1))}</div><div class="tag-list">{''.join(f'<span class="tag">{escape(x)}</span>' for x in s['frameworks'])}</div><p style="margin-top:18px;font-size:12px">Reference to recognized guidance or selected control expectations does not itself establish or guarantee compliance.</p></div></section>'''
    related=[x for x in SERVICES if x['slug']!=s['slug']][:3]
    body+=f'''<section class="section section-border"><div class="container">{section_head('Related services','Connect findings across adjacent control layers.','A combined scope may be appropriate when the decision spans systems, people, facilities, wireless, or governance.')}<div class="grid-3">{''.join(service_card(prefix,x,i) for i,x in enumerate(related,1))}</div></div></section>'''
    body+=f'''<section class="section section-border"><div class="narrow">{section_head('Service questions',f'Common questions about {escape(s["title"]).lower()}.','')}{faq_html(s['faqs'])}</div></section>'''+cta(prefix)
    page(route,s['title']+' Services',s['summary'],body,'services')

def industries_hub():
    prefix='../'
    body=hero(prefix,'Industries served','Security assessment shaped around <span class="text-gradient">operational reality.</span>','PDDG supports regulated and operationally sensitive organizations with assessment planning, safeguards, evidence, and reporting that reflect the environment being protected.',[button('Discuss Your Environment',href(prefix,'book-a-security-fit-call')),button('View Services',href(prefix,'services'),True)],crumbs=[('Home',''),('Industries',None)])
    cards=''.join(f'''<a class="industry-card reveal" href="{href(prefix,'industries/'+x['slug'])}"><span class="eyebrow">{i:02} · Industry</span><h3>{escape(x['title'])}</h3><p>{escape(x['summary'])}</p><span class="card-link">Explore {escape(x['title'])} <span>↗</span></span></a>''' for i,x in enumerate(INDUSTRIES,1))
    body+=f'''<section class="section section-border"><div class="container">{section_head('Sector context','One methodology. Different operational constraints.','Scope, methods, testing windows, evidence, stakeholders, and reporting should reflect the organization’s operational and regulatory context.')}<div class="industry-grid">{cards}</div></div></section>'''
    body+=f'''<section class="section section-dark"><div class="container">{section_head('Cross-sector principle','Protect the mission while evaluating the controls.','Methods, scheduling, evidence, and escalation must fit the environment. Assessment supports decision-making; it does not guarantee compliance or eliminate risk.')}<div class="grid-3"><article class="card card-pad reveal"><span class="eyebrow">01 · Authorization</span><h3>Define the boundary before testing.</h3><p>Assets, facilities, methods, identities, locations, time windows, exclusions, and stop conditions must be explicit.</p></article><article class="card card-pad reveal"><span class="eyebrow">02 · Safeguards</span><h3>Respect operational constraints.</h3><p>Testing methods, evidence, escalation, and scheduling should protect critical operations and sensitive information.</p></article><article class="card card-pad reveal"><span class="eyebrow">03 · Decisions</span><h3>Frame findings for action.</h3><p>Connect evidence to business impact, accountable ownership, remediation sequence, and validation expectations.</p></article></div></div></section>'''+cta(prefix)
    page('industries','Industries Served','Cybersecurity assessments shaped around regulatory, operational, and mission-specific constraints.',body,'industries')

def industry_page(x):
    route='industries/'+x['slug']; prefix='../../'
    body=hero(prefix,x['title']+' cybersecurity',escape(x['headline']),x['summary'],[button('Discuss your environment',href(prefix,'book-a-security-fit-call')),button('All industries',href(prefix,'industries'),True)],crumbs=[('Home',''),('Industries','industries'),(x['title'],None)])
    body+=f'''<section class="section section-border"><div class="container">{section_head('Operating pressures',f'Security priorities shaped by the realities of {escape(x["title"]).lower()}.','')}{detail_cards(x['pressures'])}</div></section>'''
    body+=f'''<section class="section section-dark"><div class="container">{section_head('Connected environment','Bring the right operational voices into scope.','Review the connected environment—not isolated tools.')}<div class="split-panel"><div class="split-side reveal"><span class="mono">Decision-makers</span><h3>Stakeholders who shape the scope.</h3>{list_html(x['decision'],'split-list')}</div><div class="split-side reveal"><span class="mono">Typical attack surfaces</span><h3>Systems, people, and places that connect.</h3>{list_html(x['surfaces'],'split-list')}</div></div></div></section>'''
    recommended=[SERVICE_MAP[s] for s in x['services']]
    body+=f'''<section class="section section-border"><div class="container">{section_head('Recommended assessment combination','Build coverage around the organization’s actual decision.','The right combination depends on objectives, risk, assets, authorization, and operational constraints.')}<div class="grid-4">{''.join(service_card(prefix,s,i) for i,s in enumerate(recommended,1))}</div></div></section>'''
    body+=f'''<section class="section section-dark"><div class="container">{section_head('Engagement considerations','Protect the mission while evaluating the controls.','Methods, scheduling, evidence, and escalation must fit the environment. Assessment supports decision-making; it does not guarantee compliance or eliminate risk.')}{detail_cards(x['considerations'])}</div></section>'''
    body+=f'''<section class="section section-border"><div class="container">{section_head('Expected business value','Make technical findings useful to operational leadership.','')}<div class="grid-3">{''.join(f'<article class="card card-pad reveal"><span class="eyebrow">{i:02}</span><h3>{escape(v)}</h3></article>' for i,v in enumerate(x['value'],1))}</div></div></section>'''
    ind_article='an' if x['title'][0].lower() in 'aeiou' else 'a'
    faqs=[(f'Can an assessment be tailored to {ind_article} {x["title"].lower()} environment?','Yes. Scope, methods, testing windows, evidence, stakeholders, and reporting should reflect the organization’s operational and regulatory context.'),('Does an assessment guarantee compliance?','No. An assessment can identify gaps and support readiness, but compliance depends on the applicable requirements, implemented controls, evidence, legal interpretation, and ongoing operation.'),('How are sensitive operations protected during testing?','Authorization, exclusions, safe testing methods, stop conditions, escalation contacts, data-handling expectations, and operational windows are established before work begins.')]
    body+=f'''<section class="section section-border"><div class="narrow">{section_head(x['title']+' assessment FAQ','Questions to resolve before scoping.','')}{faq_html(faqs)}</div></section>'''+cta(prefix)
    page(route,x['title']+' Cybersecurity Assessment',x['summary'],body,'industries')

def approach_page():
    prefix='../'
    body=hero(prefix,'Our approach','From technical evidence to <span class="text-gradient">clear business action.</span>','PDDG uses a structured, risk-driven approach to define scope, evaluate exposure, connect findings to business context, support remediation, and validate improvement.',[button('Book a Security Fit Call',href(prefix,'book-a-security-fit-call')),button('Explore Services',href(prefix,'services'),True)],crumbs=[('Home',''),('Approach',None)])
    body+=f'''<section class="section section-border"><div class="container">{section_head('Engagement process','A five-stage path from uncertainty to accountable action.','Each stage connects technical evidence to a clear decision, responsible owner, and measurable next action.')}{process_html()}</div></section>'''
    matrix=''.join(f'<div class="matrix-cell">{text}</div>' for text in ['Monitor','Plan','Prioritize','Plan','Prioritize','Accelerate','Prioritize','Accelerate','Immediate decision'])
    body+=f'''<section class="section section-dark"><div class="container">{section_head('Risk prioritization','Technical severity is not the final decision.','PDDG considers likelihood and exploitability alongside business impact, exposure, compensating controls, urgency, dependencies, and remediation effort.')}<div class="matrix reveal"><div class="matrix-y">Business impact</div><div class="matrix-main"><div class="matrix-grid">{matrix}</div><div class="matrix-x">Likelihood & exploitability</div><div class="matrix-labels"><span>Low</span><span>Moderate</span><span>High</span></div></div></div><div class="tag-list"><span class="tag">Asset importance</span><span class="tag">Data sensitivity</span><span class="tag">Operational impact</span><span class="tag">Exposure</span><span class="tag">Compensating controls</span><span class="tag">Remediation effort</span></div></div></section>'''
    body+=f'''<section class="section section-border"><div class="container">{section_head('Reporting audiences','One evidence base. Two decision views.','Technical and executive audiences need different framing without losing traceability to the underlying evidence.')}<div class="split-panel"><div class="split-side reveal"><span class="mono">Technical teams</span><h3>Reproduce, remediate, and validate.</h3>{list_html(['Affected assets and conditions','Reproducible technical evidence','Practical remediation guidance','Validation and retest status'],'split-list')}</div><div class="split-side reveal"><span class="mono">Executive teams</span><h3>Understand material exposure and ownership.</h3>{list_html(['Business and operational impact','Priority and urgency context','Accountable ownership','Remaining risk and next decision'],'split-list')}</div></div></div></section>'''
    body+=f'''<section class="section section-dark"><div class="container">{section_head('Evidence handling','Collect only what is necessary to support the finding.','Evidence practices are established during scoping and may include minimization, redaction, approved storage, secure transfer, access controls, retention periods, and destruction expectations.')}<div class="grid-3"><article class="card card-pad reveal"><span class="eyebrow">Minimize</span><h3>Limit sensitive information.</h3><p>Collect proportionate evidence and avoid unnecessary personal, regulated, or operational data.</p></article><article class="card card-pad reveal"><span class="eyebrow">Protect</span><h3>Control storage and transfer.</h3><p>Use agreed channels, access restrictions, handling expectations, and retention periods.</p></article><article class="card card-pad reveal"><span class="eyebrow">Explain</span><h3>State limitations clearly.</h3><p>Document assumptions, exclusions, constraints, and what the assessment does not establish.</p></article></div></div></section>'''+cta(prefix)
    page('approach','Our Risk-Driven Approach','A structured, authorized approach connecting technical evidence to business impact and practical remediation.',body,'approach')

def resources_hub():
    prefix='../'
    body=hero(prefix,'Resources','Practical guidance for <span class="text-gradient">better security decisions.</span>','Use these guides, checklists, and decision briefs to prepare for assessments, evaluate reporting, prioritize findings, and strengthen security programs.',[button('Request a Sample Report',href(prefix,'request-a-sample-report')),button('Book a Security Fit Call',href(prefix,'book-a-security-fit-call'),True)],crumbs=[('Home',''),('Resources',None)])
    body+=f'''<section class="section section-border"><div class="container">{section_head('Resource library','Start with the decision you are preparing to make.','Content is educational and general. It does not replace organization-specific assessment, legal advice, or compliance interpretation.')}<div class="resource-grid">{''.join(resource_card(prefix,r,i) for i,r in enumerate(RESOURCES,1))}</div></div></section>'''+cta(prefix)
    page('resources','Cybersecurity Resources','Practical guides, checklists, and decision briefs for cybersecurity assessment and remediation planning.',body,'resources')

def resource_page(r):
    route='resources/'+r['slug']; prefix='../../'
    body=hero(prefix,r['type'],escape(r['title']),r['summary'],[button('Book a Security Fit Call',href(prefix,'book-a-security-fit-call')),button('All resources',href(prefix,'resources'),True)],crumbs=[('Home',''),('Resources','resources'),(r['title'],None)])
    if 'checklist' in r:
        checks=''.join(f'''<label class="card" style="display:flex;gap:15px;align-items:flex-start;padding:18px;cursor:pointer"><input type="checkbox" style="margin-top:5px;accent-color:#2ce6d1"><span>{escape(x)}</span></label>''' for x in r['checklist'])
        content=f'''<section class="section section-border"><div class="article"><div class="article-intro">Use the checklist to prepare a focused, authorized, and operationally responsible assessment. Your progress is stored only in your browser.</div><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:24px"><span class="eyebrow">Readiness items</span><strong data-check-count>0 / {len(r['checklist'])}</strong></div><div data-checklist style="display:grid;gap:10px">{checks}</div><div class="article-note">Do not submit credentials, vulnerability details, protected information, or sensitive operational data through a public website form.</div></div></section>'''
    else:
        blocks=''.join(f'''<section class="article-block reveal"><h2>{escape(t)}</h2><p>{escape(p)}</p></section>''' for t,p in r['sections'])
        content=f'''<section class="section section-border"><article class="article"><p class="article-intro">{escape(r['summary'])}</p>{blocks}<div class="article-note">This resource provides general educational information. Scope, authorization, testing methods, evidence, and reporting should be tailored to the organization and engagement.</div></article></section>'''
    body+=content+cta(prefix)
    page(route,r['title'],r['summary'],body,'resources')

def about_page():
    prefix='../'
    summary='Pinnacle Digital Defense Group helps regulated and operationally sensitive organizations understand cybersecurity exposure, prioritize risk, and move from findings to practical action.'
    body=hero(prefix,'About PDDG','Independent assessment. <span class="text-gradient">Clearer decisions.</span>',summary,[button('Book a Security Fit Call',href(prefix,'book-a-security-fit-call')),button('View Our Approach',href(prefix,'approach'),True)],crumbs=[('Home',''),('About',None)])
    body+=f'''<section class="section section-border"><div class="container">{section_head('Our purpose','Make security evidence useful to the people responsible for action.','PDDG focuses on authorized assessment, defensible evidence, business context, practical remediation guidance, and reporting that supports technical and executive decisions.')}<div class="grid-3"><article class="card card-pad reveal"><span class="eyebrow">01 · Independence</span><h3>Evidence before assumption.</h3><p>Findings are framed around observed conditions, approved validation, stated limitations, and the decision the engagement must support.</p></article><article class="card card-pad reveal"><span class="eyebrow">02 · Restraint</span><h3>Testing without unnecessary risk.</h3><p>Authorization, exclusions, safe methods, stop conditions, escalation, and evidence handling are established before active work.</p></article><article class="card card-pad reveal"><span class="eyebrow">03 · Action</span><h3>Recommendations that fit reality.</h3><p>Priorities account for exploitability, business impact, operational constraints, ownership, dependencies, and remediation effort.</p></article></div></div></section>'''
    body+=f'''<section class="section section-dark"><div class="container">{section_head('Expertise','Coverage across connected control layers.','Organizations are exposed through systems, applications, people, policies, facilities, wireless environments, vendors, and the decisions connecting them.')}<div class="grid-3">{''.join(service_card(prefix,s,i) for i,s in enumerate(SERVICES[:6],1))}</div></div></section>'''
    body+=f'''<section class="section-tight section-border"><div class="container">{section_head('Professional credentials','Capability supported by continued professional development.','Credentials are presented as evidence of professional study and qualification—not as a guarantee of outcomes or compliance.')}{credentials(prefix)}</div></section>'''+cta(prefix)
    page('about','About Pinnacle Digital Defense Group',summary,body,'about')

def form_page(route, title, eyebrow, headline, summary, form_subject, fields, active='contact', note='Do not include credentials, vulnerability details, protected information, or sensitive operational data in this form.'):
    prefix=depth_prefix(route)
    form_fields=''
    for field in fields:
        kind,name,label,full,options=field
        cls='field full' if full else 'field'
        if kind=='textarea': control=f'<textarea id="{name}" name="{label}" required></textarea>'
        elif kind=='select': control=f'<select id="{name}" name="{label}" required><option value="">Select an option</option>'+''.join(f'<option>{escape(o)}</option>' for o in options)+'</select>'
        else: control=f'<input id="{name}" name="{label}" type="{kind}" required>'
        form_fields+=f'<div class="{cls}"><label for="{name}">{escape(label)}</label>{control}</div>'
    form=f'''<form class="form-card reveal" data-mail-form data-subject="{escape(form_subject)}"><div class="form-grid">{form_fields}</div><p class="form-note">{escape(note)}</p><button class="btn" type="submit">Prepare email {ARROW}</button><div class="form-status" role="status"></div></form>'''
    body=hero(prefix,eyebrow,headline,summary,[button('Call '+COMPANY['phone'],'tel:+13015321463',True)],crumbs=[('Home',''),(title,None)])
    body+=f'''<section class="section section-border"><div class="container contact-grid"><aside class="contact-info reveal"><div class="contact-chip"><small>Phone</small><a href="tel:+13015321463">{COMPANY['phone']}</a></div><div class="contact-chip"><small>Email</small><a href="mailto:{COMPANY['email']}">{COMPANY['email']}</a></div><div class="contact-chip"><small>Office</small><strong>{COMPANY['address']}</strong></div><div class="contact-chip"><small>Hours</small><strong>{COMPANY['hours']}</strong></div><div class="article-note" style="margin-top:4px">For an urgent or active security incident, call rather than relying on a website form. Incident-response availability must be confirmed separately.</div></aside>{form}</div></section>'''+cta(prefix,'Need a different starting point?','Review the service and industry pages, or call PDDG to discuss the most appropriate next step.')
    page(route,title,summary,body,active)

def general_pages():
    form_page('contact','Contact PDDG','Contact','Start a clear conversation about your security objective.','Share the decision you need to make, the general environment, and the type of guidance you are seeking.','PDDG website contact',[('text','name','Name',False,[]),('email','email','Email',False,[]),('text','organization','Organization',False,[]),('tel','phone','Phone',False,[]),('select','interest','Area of interest',True,[s['title'] for s in SERVICES]+['Not sure yet']),('textarea','message','How can PDDG help?',True,[])])
    form_page('book-a-security-fit-call','Book a Security Fit Call','Security Fit Call','Clarify the decision before defining the assessment.','Use a focused conversation to discuss your objective, environment, constraints, stakeholders, and the assessment path that may fit.','Security Fit Call request',[('text','name','Name',False,[]),('email','email','Business email',False,[]),('text','organization','Organization',False,[]),('tel','phone','Phone',False,[]),('select','service','Service of interest',True,[s['title'] for s in SERVICES]+['Not sure yet']),('textarea','objective','What decision or concern should the call address?',True,[])],active='contact')
    form_page('request-a-sample-report','Request a Sample Report','Sample report','Review how evidence, impact, priority, ownership, and remediation can be structured.','Request a sanitized sample report to evaluate the reporting approach for technical and executive audiences.','Sample report request',[('text','name','Name',False,[]),('email','email','Business email',False,[]),('text','organization','Organization',False,[]),('select','audience','Primary audience',False,['Technical','Executive','Both']),('textarea','context','What would you like to evaluate in the sample?',True,[])],active='resources')

def faq_page():
    prefix='../'
    items=[('What services does PDDG provide?','PDDG provides penetration testing, vulnerability assessment, vulnerability management, web application security assessment, threat intelligence and monitoring, security awareness training, physical security assessment, cybersecurity policy assessment, and wireless and Bluetooth security audit services.'),('How is scope established?','Objectives, stakeholders, assets, facilities, identities, locations, methods, exclusions, testing windows, safeguards, escalation, evidence, and deliverables are confirmed before active work begins.'),('Does an assessment guarantee security or compliance?','No. Assessment provides evidence within an agreed scope and time window. It cannot eliminate risk or guarantee compliance, which depends on applicable requirements, implementation, evidence, legal interpretation, and continued operation.'),('How are findings prioritized?','Technical severity is considered alongside likelihood, exploitability, business impact, exposure, compensating controls, urgency, dependencies, ownership, and remediation effort.'),('Can PDDG retest findings?','Retesting may be included when agreed in scope. The retest window, eligible findings, evidence requirements, and reporting method should be stated in the engagement.'),('How is sensitive evidence handled?','Evidence expectations may include minimization, redaction, approved storage and transfer, access controls, retention, and destruction. Exact requirements are confirmed during scoping.'),('Can multiple services be combined?','Yes. A combined scope may be useful when the decision spans systems, applications, people, policies, facilities, wireless environments, or ongoing remediation.')]
    body=hero(prefix,'Frequently asked questions','Resolve the questions that protect the <span class="text-gradient">engagement.</span>','Review common questions about scope, authorization, safeguards, evidence, priorities, reporting, compliance limitations, and next steps.',[button('Book a Security Fit Call',href(prefix,'book-a-security-fit-call'))],crumbs=[('Home',''),('FAQs',None)])
    body+=f'''<section class="section section-border"><div class="narrow">{faq_html(items)}</div></section>'''+cta(prefix)
    page('frequently-asked-questions','Frequently Asked Questions','Common questions about PDDG cybersecurity assessments, scope, authorization, evidence, and reporting.',body,'resources')

def case_studies_page():
    prefix='../'
    body=hero(prefix,'Case studies','Evidence without exposing client confidentiality.','PDDG does not publish client names, sensitive environments, unsupported outcomes, or identifying engagement details without explicit approval.',[button('Discuss Your Environment',href(prefix,'book-a-security-fit-call')),button('Request a Sample Report',href(prefix,'request-a-sample-report'),True)],crumbs=[('Home',''),('Case Studies',None)])
    body+=f'''<section class="section section-border"><div class="container">{section_head('Publication standard','Credibility should not require oversharing.','Future case studies will use approved, sanitized information and will distinguish observed facts, client-approved outcomes, limitations, and context.')}<div class="grid-3"><article class="card card-pad reveal"><span class="eyebrow">Protect</span><h3>Client identity and sensitive context.</h3><p>Names, systems, facilities, findings, and outcomes are not published without explicit permission.</p></article><article class="card card-pad reveal"><span class="eyebrow">Substantiate</span><h3>Claims with approved evidence.</h3><p>Metrics and outcomes must be supportable, attributable, and presented with the relevant limitations.</p></article><article class="card card-pad reveal"><span class="eyebrow">Explain</span><h3>The decision and method.</h3><p>Useful case studies show the objective, constraints, assessment path, output, and what changed—without exposing operational detail.</p></article></div></div></section>'''+cta(prefix)
    page('case-studies','Cybersecurity Case Studies','PDDG case study publication standards and sanitized engagement evidence.',body,'about')

def legal_page(route,title,intro,sections):
    prefix='../'
    body=hero(prefix,'Legal and governance',escape(title),intro,[button('Contact PDDG',href(prefix,'contact'))],crumbs=[('Home',''),(title,None)])
    blocks=''.join(f'<section class="article-block"><h2>{escape(h)}</h2>'+''.join(f'<p style="margin-top:14px">{escape(p)}</p>' for p in paras)+'</section>' for h,paras in sections)
    body+=f'<section class="section section-border"><article class="article"><p class="article-intro">{escape(intro)}</p>{blocks}</article></section>'
    page(route,title,intro,body,'about')

def legal_pages():
    legal_page('privacy-policy','Privacy Policy','This policy explains how information submitted through or associated with the PDDG website may be handled.',[
      ('Information you provide',['You may provide contact information and a general description of your inquiry when contacting PDDG. Do not submit credentials, vulnerability details, protected information, regulated data, or sensitive operational information through a public website form.','In this static redesign, form submissions are prepared in your local email application and are not stored by the website itself. Your email provider and PDDG email systems may process the message you choose to send.']),
      ('Technical information',['The hosting platform and ordinary internet infrastructure may process technical information such as IP address, browser type, device information, requested pages, timestamps, and security logs. PDDG does not use this website to intentionally collect sensitive assessment evidence.']),
      ('How information may be used',['Information may be used to respond to inquiries, evaluate service fit, maintain business records, protect systems, meet legal obligations, and improve communications. Information is not presented as being sold to advertisers.']),
      ('Security and retention',['Reasonable safeguards may be used, but no internet transmission or storage system can be guaranteed secure. Retention depends on business, legal, security, and operational requirements.']),
      ('Contact',['Questions about this policy may be directed to Info@pddg.io or 301-532-1463.'])])
    legal_page('terms-and-conditions','Terms & Conditions','These terms govern use of the public PDDG website and do not create a cybersecurity assessment engagement.',[
      ('Informational use',['Website content is general information and is not legal advice, compliance advice, a security guarantee, or a substitute for an authorized, scoped assessment.']),
      ('No engagement by website use',['Submitting an inquiry, requesting a call, or reviewing website content does not create an engagement, duty, confidentiality obligation beyond applicable law, or authorization to test systems. Services require written agreement, scope, authorization, safeguards, and commercial terms.']),
      ('Acceptable use',['Do not misuse the website, attempt unauthorized access, interfere with availability, submit unlawful content, or send credentials, vulnerability details, protected information, or sensitive operational data through public forms.']),
      ('Intellectual property',['Website design, branding, and original content are owned by or licensed to PDDG unless otherwise stated. Limited personal and business review is permitted; copying or redistribution may require permission.']),
      ('Limitations',['The website is provided without a guarantee of uninterrupted availability, completeness, or fitness for a particular purpose. References to frameworks do not establish or guarantee compliance.'])])
    legal_page('accessibility-statement','Accessibility Statement','PDDG aims to provide a website that is usable by people with a range of abilities, devices, and assistive technologies.',[
      ('Design approach',['The redesign uses semantic headings, keyboard-accessible navigation, visible focus states, labelled controls, text alternatives for meaningful images, responsive layouts, and support for reduced-motion preferences.']),
      ('Ongoing improvement',['Accessibility is an ongoing process. Content, browser behavior, assistive technologies, and implementation may change over time, and issues may still occur.']),
      ('Feedback',['If you encounter an accessibility barrier, contact Info@pddg.io or 301-532-1463 and describe the page, issue, assistive technology, and preferred response method when practical.'])])

def write_assets_and_config():
    favicon='''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="15" fill="#06111d"/><path d="M32 8 52 17v14c0 13-7.5 21-20 27C19.5 52 12 44 12 31V17L32 8Z" fill="none" stroke="#2ce6d1" stroke-width="4"/><path d="M22 34 29 41 43 24" fill="none" stroke="#f2f8fb" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg>'''
    (ROOT/'assets/images/favicon.svg').write_text(favicon,encoding='utf-8')
    (ROOT/'.nojekyll').write_text('',encoding='utf-8')
    manifest='''{"name":"Pinnacle Digital Defense Group","short_name":"PDDG","start_url":"./","display":"standalone","background_color":"#02070d","theme_color":"#02070d","icons":[{"src":"assets/images/favicon.svg","sizes":"any","type":"image/svg+xml"}]}'''
    (ROOT/'site.webmanifest').write_text(manifest,encoding='utf-8')
    (ROOT/'robots.txt').write_text(f'User-agent: *\nAllow: /\nSitemap: {BASE}/sitemap.xml\n',encoding='utf-8')
    routes=['']+['services']+[f'services/{s["slug"]}' for s in SERVICES]+['industries']+[f'industries/{x["slug"]}' for x in INDUSTRIES]+['approach','resources']+[f'resources/{r["slug"]}' for r in RESOURCES]+['about','contact','book-a-security-fit-call','request-a-sample-report','case-studies','frequently-asked-questions','privacy-policy','terms-and-conditions','accessibility-statement']
    urls=''.join(f'<url><loc>{BASE}{"/"+r+"/" if r else "/"}</loc></url>' for r in routes)
    (ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls+'</urlset>',encoding='utf-8')
    workflow='''name: Deploy static site to GitHub Pages\n\non:\n  push:\n    branches: [\"main\"]\n  workflow_dispatch:\n\npermissions:\n  contents: read\n  pages: write\n  id-token: write\n\nconcurrency:\n  group: pages\n  cancel-in-progress: true\n\njobs:\n  deploy:\n    environment:\n      name: github-pages\n      url: ${{ steps.deployment.outputs.page_url }}\n    runs-on: ubuntu-latest\n    steps:\n      - name: Checkout\n        uses: actions/checkout@v4\n      - name: Configure Pages\n        uses: actions/configure-pages@v5\n      - name: Upload artifact\n        uses: actions/upload-pages-artifact@v3\n        with:\n          path: .\n      - name: Deploy to GitHub Pages\n        id: deployment\n        uses: actions/deploy-pages@v4\n'''
    (ROOT/'.github/workflows').mkdir(parents=True,exist_ok=True)
    (ROOT/'.github/workflows/deploy.yml').write_text(workflow,encoding='utf-8')
    readme='''# PDDG Premium Cybersecurity Website Redesign\n\nA complete static redesign of the Pinnacle Digital Defense Group website for GitHub Pages. The project preserves the existing service names, industry pages, core business content, legal pages, resources, contact details, and public URL structure while replacing the design and front-end experience.\n\n## Deploy to GitHub Pages\n\n1. Extract the ZIP.\n2. Replace the contents of your existing `pddg-cybersecurity` repository with the extracted files.\n3. Commit and push everything to the `main` branch.\n4. In GitHub, open **Settings → Pages**.\n5. Under **Build and deployment**, choose **GitHub Actions**.\n6. Open the **Actions** tab and confirm that “Deploy static site to GitHub Pages” completes successfully.\n\nThe site is built with plain HTML, CSS, and JavaScript, so there is no npm installation or build command.\n\n## Forms\n\nThe site is static. Contact, booking, and sample-report forms prepare an email in the visitor's email application and do not store form data on the website. For production lead capture, connect the forms to your CRM or form endpoint.\n\n## Main files\n\n- `index.html` — homepage\n- `services/`, `industries/`, `resources/` — all preserved routes\n- `assets/css/styles.css` — complete responsive design system\n- `assets/js/main.js` — animations, navigation, accordions, service tabs, checklist, and form behavior\n- `.github/workflows/deploy.yml` — automatic GitHub Pages deployment\n\n## Editing content\n\nThe generated HTML files are deployment-ready. `generate_site.py` is also included as the structured source used to generate the pages. Edit its content dictionaries and run `python generate_site.py` to regenerate the site consistently.\n'''
    (ROOT/'README.md').write_text(readme,encoding='utf-8')

def not_found():
    prefix=''
    body=hero(prefix,'404 · Page not found','The requested signal is <span class="text-gradient">outside the mapped scope.</span>','The page may have moved, or the address may be incorrect.',[button('Return home',href(prefix,'')),button('View services',href(prefix,'services'),True)],inner=False,visual='orbit')
    html=page('', 'Page Not Found', 'The requested page could not be found.', body, 'home')
    # page() wrote index, so write separately using a compact duplicate built from existing index shell.
    source=(ROOT/'index.html').read_text(encoding='utf-8')
    start=source.find('<main id="main">')+len('<main id="main">')
    end=source.find('</main>',start)
    custom=source[:start]+body+source[end:]
    (ROOT/'404.html').write_text(custom.replace('<title>Risk-Driven Cybersecurity Assessments | PDDG</title>','<title>Page Not Found | PDDG</title>',1),encoding='utf-8')


def main():
    write_assets_and_config()
    home_page()
    services_hub()
    for s in SERVICES: service_page(s)
    industries_hub()
    for x in INDUSTRIES: industry_page(x)
    approach_page()
    resources_hub()
    for r in RESOURCES: resource_page(r)
    about_page()
    general_pages()
    faq_page()
    case_studies_page()
    legal_pages()
    # build 404 from current index without overwriting root page
    source=(ROOT/'index.html').read_text(encoding='utf-8')
    prefix=''
    b=hero(prefix,'404 · Page not found','The requested signal is <span class="text-gradient">outside the mapped scope.</span>','The page may have moved, or the address may be incorrect.',[button('Return home',href(prefix,'')),button('View services',href(prefix,'services'),True)],inner=False,visual='orbit')
    st=source.find('<main id="main">')+len('<main id="main">'); en=source.find('</main>',st)
    (ROOT/'404.html').write_text(source[:st]+b+source[en:],encoding='utf-8')
    print('Generated site:', ROOT)

if __name__=='__main__':
    main()
