import Link from 'next/link';
import { Accordion } from '@/components/Interactive';
import { Credentials, HeroVisual, IndustryGrid, Process, ReportPreview, SectionIntro, ServiceGrid, Icon } from '@/components/Elements';
import { generalFaq, resources } from '@/lib/content';

export default function HomePage() {
  return <>
    <section className="home-hero dark-section"><div className="container"><div className="hero-copy"><span className="eyebrow light">Independent · Risk-driven · Actionable</span><h1>Know where your organization is exposed—<em>and what to fix first.</em></h1><p className="hero-lede">PDDG delivers cybersecurity assessments, threat monitoring, security training, policy reviews, and physical-security evaluations for organizations that need clearer priorities and practical remediation guidance.</p><div className="hero-actions"><Link href="/book-a-security-fit-call" className="button">Book a Security Fit Call <span>↗</span></Link><Link href="/services" className="button button-ghost">Explore Our Security Services</Link></div><p className="hero-note"><Icon name="shield"/> Initial consultations focus on understanding your requirements and discussing appropriate next steps.</p></div><HeroVisual variant="matrix" label="Security exposure"/></div><div className="hero-metrics container"><span><b>Digital</b> systems & applications</span><span><b>Human</b> awareness & procedures</span><span><b>Physical</b> facilities & wireless</span><span><b>Executive</b> risk communication</span></div></section>

    <Credentials/>

    <section className="problem-section section"><div className="container split-heading"><SectionIntro eyebrow="The operating challenge" title="Security teams do not need more noise. They need clearer priorities."/><div className="problem-copy"><p className="large-copy">Unknown vulnerabilities, disconnected tools, limited capacity, compliance pressure, human risk, and reports written only for technical readers can leave leadership with activity—but no clear decision.</p><div className="signal-list"><span><i/>What could materially affect operations?</span><span><i/>Which weaknesses create a credible path?</span><span><i/>What should be owned, sequenced, and verified?</span></div></div></div></section>

    <section className="benefits section muted"><div className="container"><SectionIntro eyebrow="From exposure to action" title="Assessment work designed to support better decisions." copy="PDDG connects technical evidence to practical business context so teams can act with focus."/><div className="benefit-grid">
      <article><span className="icon-box"><Icon name="scan"/></span><span className="card-number">01</span><h3>Find the gaps that matter most</h3><p>Identify technical, procedural, human, wireless, and physical exposure across the approved scope.</p></article>
      <article><span className="icon-box"><Icon name="target"/></span><span className="card-number">02</span><h3>Turn findings into an actionable plan</h3><p>Prioritize remediation according to risk, impact, exploitability, urgency, ownership, and effort.</p></article>
      <article><span className="icon-box"><Icon name="chart"/></span><span className="card-number">03</span><h3>Demonstrate measurable progress</h3><p>Help executives, auditors, customers, and technical teams understand improvement and remaining risk.</p></article>
    </div></div></section>

    <section className="services-section section"><div className="container"><div className="section-heading-row"><SectionIntro eyebrow="Security services" title="Examine risk across the layers that keep the organization operating." copy="Select a focused assessment or combine services around a defined business objective."/><Link className="text-link" href="/services">View all services <Icon name="arrow"/></Link></div><ServiceGrid/></div></section>

    <section className="selection-guide dark-section section"><div className="container"><div><span className="eyebrow light">Service selection guide</span><h2>Not sure which assessment you need?</h2><p>Begin with the question you need the work to answer. A fit call can help distinguish broad discovery, controlled validation, ongoing management, governance review, monitoring, or on-site exposure.</p><Link href="/book-a-security-fit-call" className="button">Help Me Choose the Right Assessment <span>↗</span></Link></div><div className="selection-list"><span><b>Penetration testing</b><em>Validate realistic attack paths</em></span><span><b>Vulnerability assessment</b><em>Identify and prioritize broad exposure</em></span><span><b>Vulnerability management</b><em>Track risk reduction over time</em></span><span><b>Policy assessment</b><em>Review governance and procedures</em></span><span><b>Wireless & physical</b><em>Assess on-site and infrastructure pathways</em></span></div></div></section>

    <section className="industries-section section muted"><div className="container"><div className="section-heading-row"><SectionIntro eyebrow="Industries" title="Security context changes with the mission, data, and operating environment." copy="PDDG’s assessment approach accounts for sector-specific pressures without treating a framework as a guarantee."/><Link className="text-link" href="/industries">View industries <Icon name="arrow"/></Link></div><IndustryGrid/></div></section>

    <section className="approach-section section"><div className="container"><SectionIntro eyebrow="The PDDG approach" title="A disciplined path from uncertainty to accountable action." copy="Exact stages and methods depend on the selected service, authorization, and engagement scope."/><Process/></div></section>

    <section className="report-section dark-section section"><div className="container report-layout"><div><span className="eyebrow light">Clear reporting</span><h2>Give every audience the level of detail it needs.</h2><p>Assessment output may combine an executive view, risk-prioritized findings, technical evidence, impact context, responsible owners, suggested timelines, and validation status—depending on scope.</p><ul className="check-list"><li>Executive summary</li><li>Technical evidence</li><li>Business-impact explanation</li><li>Remediation recommendations</li></ul><Link href="/request-a-sample-report" className="button">Request a Sample Report <span>↗</span></Link></div><ReportPreview/></div></section>

    <section className="resources-section section"><div className="container"><div className="section-heading-row"><SectionIntro eyebrow="Security resources" title="Make a more informed assessment decision."/><Link className="text-link" href="/resources">Browse all resources <Icon name="arrow"/></Link></div><div className="resource-grid">{resources.slice(0, 3).map((r, i) => <Link href={`/resources/${r.slug}`} className="resource-card" key={r.slug}><div className={`resource-art art-${i + 1}`}><span>{r.category}</span><i/><b>0{i + 1}</b></div><div><span className="card-kicker">{r.read} read</span><h3>{r.title}</h3><p>{r.excerpt}</p><span className="card-link">Read resource <Icon name="arrow"/></span></div></Link>)}</div></div></section>

    <section className="faq-section section muted"><div className="container faq-layout"><SectionIntro eyebrow="Frequently asked questions" title="Plan the conversation with fewer unknowns." copy="Answers are deliberately qualified because scope, timing, methods, and deliverables vary by engagement."/><Accordion items={generalFaq.slice(0, 6)}/></div></section>
  </>;
}
