import Link from 'next/link';
import type { Industry, Service } from '@/lib/content';
import { industries, services } from '@/lib/content';
import { Accordion } from './Interactive';
import { Breadcrumbs, HeroVisual, Icon, Process, SectionIntro } from './Elements';

function PillList({ items }: { items: string[] }) { return <div className="pill-list">{items.map(item => <span key={item}>{item}</span>)}</div>; }
function CheckItems({ items }: { items: string[] }) { return <ul className="detail-list">{items.map(item => <li key={item}><span>✓</span>{item}</li>)}</ul>; }

export function ServiceDetail({ service }: { service: Service }) {
  const related = service.related.map(slug => services.find(s => s.slug === slug)).filter(Boolean) as Service[];
  return <>
    <section className="detail-hero dark-section"><div className="container"><div className="hero-copy"><Breadcrumbs items={[{ label: 'Services', href: '/services' }, { label: service.name }]}/><span className="eyebrow light">{service.eyebrow}</span><h1>{service.headline}</h1><p className="hero-lede">{service.summary}</p><div className="hero-actions"><Link href="/book-a-security-fit-call" className="button">Discuss this service <span>↗</span></Link><Link href="/services" className="button button-ghost">All services</Link></div></div><HeroVisual variant={service.visual} label={service.name}/></div></section>
    <section className="detail-intro section"><div className="container two-col"><div><span className="eyebrow">Who it is for</span><h2>A focused engagement for a defined security decision.</h2></div><div><p className="large-copy">{service.ideal}</p><p className="scope-note">The exact methodology, assets, test actions, safeguards, and deliverables are confirmed during scoping.</p></div></div></section>
    <section className="detail-cards section muted"><div className="container"><SectionIntro eyebrow="Common triggers" title={`When ${service.name.toLowerCase()} may be the right next step.`}/><div className="four-grid">{service.triggers.map((item, i) => <article key={item}><span>0{i + 1}</span><h3>{item}</h3></article>)}</div></div></section>
    <section className="scope-section section"><div className="container split-panels"><div className="panel dark-panel"><span className="eyebrow light">What may be assessed</span><h2>Coverage shaped around the approved objective.</h2><CheckItems items={service.scope}/><p>Testing never extends beyond explicitly authorized systems, facilities, methods, identities, locations, or time windows.</p></div><div className="panel light-panel"><span className="eyebrow">Expected deliverables</span><h2>Evidence designed to support action.</h2><CheckItems items={service.deliverables}/><p>Specific output varies according to engagement scope and the needs of executive and technical audiences.</p></div></div></section>
    <section className="method-section section"><div className="container"><SectionIntro eyebrow="Methodology" title="Structured, authorized, and grounded in business context." copy="The process adapts to the selected service and environment. No active testing begins without an agreed scope and rules of engagement."/><Process compact/></div></section>
    <section className="benefit-band dark-section section"><div className="container"><div><span className="eyebrow light">Business value</span><h2>Use the findings to make a clearer risk decision.</h2></div><div className="number-list">{service.benefits.map((item, i) => <span key={item}><b>{String(i + 1).padStart(2, '0')}</b>{item}</span>)}</div></div></section>
    <section className="standards-section section muted"><div className="container two-col"><div><span className="eyebrow">Governance context</span><h2>Relevant references, applied carefully.</h2><p>Depending on scope, assessment planning and reporting may reference recognized guidance or selected control expectations. Reference does not itself establish or guarantee compliance.</p></div><PillList items={service.standards}/></div></section>
    <section className="related-section section"><div className="container"><SectionIntro eyebrow="Related services" title="Connect findings across adjacent control layers."/><div className="three-grid">{related.map(item => <Link className="related-card" href={`/services/${item.slug}`} key={item.slug}><span>{item.eyebrow}</span><h3>{item.name}</h3><p>{item.summary}</p><b>View service <Icon name="arrow"/></b></Link>)}</div></div></section>
    <section className="faq-section section muted"><div className="container faq-layout"><SectionIntro eyebrow="Service questions" title={`Common questions about ${service.name.toLowerCase()}.`}/><Accordion items={service.faq}/></div></section>
  </>;
}

export function IndustryDetail({ industry }: { industry: Industry }) {
  const related = industry.services.map(slug => services.find(s => s.slug === slug)).filter(Boolean) as Service[];
  return <>
    <section className="detail-hero industry-detail-hero dark-section"><div className="container"><div className="hero-copy"><Breadcrumbs items={[{ label: 'Industries', href: '/industries' }, { label: industry.name }]}/><span className="eyebrow light">{industry.name} cybersecurity</span><h1>{industry.headline}</h1><p className="hero-lede">{industry.summary}</p><div className="hero-actions"><Link href="/book-a-security-fit-call" className="button">Discuss your environment <span>↗</span></Link><Link href="/industries" className="button button-ghost">All industries</Link></div></div><HeroVisual variant={industry.visual} label={`${industry.name} risk`}/></div></section>
    <section className="sector-pressure section"><div className="container"><SectionIntro eyebrow="Operating pressures" title={`Security priorities shaped by the realities of ${industry.name.toLowerCase()}.`}/><div className="four-grid">{industry.pressures.map((item, i) => <article key={item}><span>0{i + 1}</span><h3>{item}</h3></article>)}</div></div></section>
    <section className="sector-map section muted"><div className="container split-panels"><div className="panel dark-panel"><span className="eyebrow light">Decision-makers</span><h2>Bring the right operational voices into scope.</h2><CheckItems items={industry.leaders}/></div><div className="panel light-panel"><span className="eyebrow">Typical attack surfaces</span><h2>Review the connected environment—not isolated tools.</h2><CheckItems items={industry.surfaces}/></div></div></section>
    <section className="sector-services section"><div className="container"><SectionIntro eyebrow="Recommended assessment combination" title="Build coverage around the organization’s actual decision." copy="The right combination depends on objectives, risk, assets, authorization, and operational constraints."/><div className="service-grid compact-grid">{related.map((item, i) => <Link href={`/services/${item.slug}`} className="service-card" key={item.slug}><div className="card-top"><span className="icon-box"><Icon name={i % 2 ? 'scan' : 'shield'}/></span><span className="card-number">0{i + 1}</span></div><h3>{item.name}</h3><p>{item.summary}</p><span className="card-link">View service <Icon name="arrow"/></span></Link>)}</div></div></section>
    <section className="considerations dark-section section"><div className="container two-col"><div><span className="eyebrow light">Engagement considerations</span><h2>Protect the mission while evaluating the controls.</h2><p>Methods, scheduling, evidence, and escalation must fit the environment. Assessment supports decision-making; it does not guarantee compliance or eliminate risk.</p></div><div className="number-list">{industry.considerations.map((item, i) => <span key={item}><b>{String(i + 1).padStart(2, '0')}</b>{item}</span>)}</div></div></section>
    <section className="value-section section muted"><div className="container two-col"><div><span className="eyebrow">Expected business value</span><h2>Make technical findings useful to operational leadership.</h2></div><CheckItems items={industry.value}/></div></section>
    <section className="faq-section section"><div className="container faq-layout"><SectionIntro eyebrow={`${industry.name} assessment FAQ`} title="Questions to resolve before scoping."/><Accordion items={[
      { q: `Can an assessment be tailored to a ${industry.name.toLowerCase()} environment?`, a: 'Yes. Scope, methods, testing windows, evidence, stakeholders, and reporting should reflect the organization’s operational and regulatory context.' },
      { q: 'Does an assessment guarantee compliance?', a: 'No. An assessment can identify gaps and support readiness, but compliance depends on the applicable requirements, implemented controls, evidence, legal interpretation, and ongoing operation.' },
      { q: 'How are sensitive operations protected during testing?', a: 'Authorization, exclusions, safe testing methods, stop conditions, escalation contacts, data-handling expectations, and operational windows are established before work begins.' }
    ]}/></div></section>
  </>;
}
