import Link from 'next/link';
import { Accordion, DemoForm } from './Interactive';
import { Breadcrumbs, Credentials, IndustryGrid, PageHero, Process, ReportPreview, SectionIntro, ServiceGrid, Icon } from './Elements';
import { generalFaq, industries, readinessItems, resources, services, site } from '@/lib/content';

export function ServicesPage() {
  return <><PageHero eyebrow="Security services" title="Identify the gaps, understand the risk, and act in the right order." copy="PDDG evaluates digital, procedural, human, wireless, and physical exposure—then translates findings into practical remediation priorities." secondary="Help me choose" secondaryHref="/book-a-security-fit-call" visual="path"/><section className="section"><div className="container"><SectionIntro eyebrow="Assess · Strengthen · Monitor" title="Coverage across the layers that shape operational risk." copy="Every engagement is scoped around a defined objective, authorized environment, and intended decision."/><ServiceGrid/></div></section><section className="selection-guide dark-section section"><div className="container"><div><span className="eyebrow light">Choose by objective</span><h2>Start with the question—not the tool.</h2><p>Broad discovery, controlled exploitation, application logic, human behavior, governance, wireless exposure, facility controls, and ongoing visibility answer different questions.</p><Link className="button" href="/book-a-security-fit-call">Discuss the right assessment <span>↗</span></Link></div><div className="selection-list"><span><b>Find broad exposure</b><em>Vulnerability Assessment</em></span><span><b>Validate attack paths</b><em>Penetration Testing</em></span><span><b>Improve governance</b><em>Cybersecurity Policy Assessment</em></span><span><b>Build ongoing visibility</b><em>Vulnerability Management or Threat Monitoring</em></span></div></div></section><section className="section muted"><div className="container"><SectionIntro eyebrow="Engagement process" title="A consistent decision framework, adapted to the service."/><Process compact/></div></section><Credentials/></>;
}

export function IndustriesPage() {
  return <><PageHero eyebrow="Industries" title="Cybersecurity assessments shaped around how your organization actually operates." copy="PDDG works across regulated and operationally sensitive environments where systems, people, facilities, data, vendors, and mission continuity must be considered together." visual="facility"/><section className="section muted"><div className="container"><SectionIntro eyebrow="Sector context" title="Six environments. Six different operating realities." copy="Each industry page connects common pressures, decision-makers, attack surfaces, services, and engagement constraints."/><IndustryGrid/></div></section><section className="section"><div className="container two-col"><div><span className="eyebrow">Cross-sector principle</span><h2>Frameworks inform the work. Business context determines the priority.</h2></div><div><p className="large-copy">A high technical score does not automatically describe operational consequence. PDDG considers exposed assets, mission impact, exploitability, compensating controls, ownership, and remediation feasibility.</p><Link href="/approach" className="text-link">See the PDDG approach <Icon name="arrow"/></Link></div></div></section></>;
}

export function ApproachPage() {
  return <><PageHero eyebrow="Our approach" title="A risk-driven process built for technical depth and executive clarity." copy="PDDG develops scope around the decision you need to make, validates findings carefully, and organizes remediation around business impact—not scanner volume." visual="cycle"/><section className="section"><div className="container"><SectionIntro eyebrow="Discover → Assess → Prioritize → Remediate → Validate" title="A disciplined path from uncertainty to accountable action." copy="This visual framework has the same text sequence below for screen readers and non-visual use."/><Process/></div></section><section className="section muted"><div className="container"><SectionIntro eyebrow="How priorities are evaluated" title="Severity is one input. Context makes it a decision."/><div className="priority-matrix"><div className="matrix-label y">Business impact</div><div className="matrix-grid"><span className="m-low">Monitor</span><span className="m-med">Plan</span><span className="m-med">Plan</span><span className="m-high">Prioritize</span><span className="m-med">Plan</span><span className="m-high">Prioritize</span><span className="m-high">Prioritize</span><span className="m-critical">Act first</span><span className="m-high">Prioritize</span></div><div className="matrix-label x">Likelihood & exploitability →</div><aside><b>Context considered</b><span>Asset importance</span><span>External exposure</span><span>Attack-path position</span><span>Compensating controls</span><span>Operational consequence</span><span>Remediation effort</span></aside></div></div></section><section className="section"><div className="container split-panels"><div className="panel dark-panel"><span className="eyebrow light">Technical teams</span><h2>Reproducible evidence and practical recommendations.</h2><p>Findings may include affected components, conditions, evidence, impact, remediation direction, ownership context, and validation status depending on scope.</p></div><div className="panel light-panel"><span className="eyebrow">Executive teams</span><h2>Risk language aligned to decisions and accountability.</h2><p>Executive communication focuses on material exposure, affected operations, priority, responsible ownership, expected action, and remaining risk.</p></div></div></section><section className="benefit-band dark-section section"><div className="container two-col"><div><span className="eyebrow light">Sensitive information</span><h2>Evidence handling begins with restraint.</h2></div><div><p>Engagement-specific handling, approved channels, access, retention, evidence minimization, and delivery methods are established during contracting and scoping. Public forms should never be used to send sensitive findings or credentials.</p></div></div></section></>;
}

export function AboutPage() {
  return <><PageHero eyebrow="About PDDG" title="Technical assessment with the context to support informed security decisions." copy="Pinnacle Digital Defense Group provides tailored cybersecurity services that examine digital and physical environments, identify critical vulnerabilities, and recommend practical protection strategies." visual="shield"/><section className="section"><div className="container two-col"><div><span className="eyebrow">Why PDDG exists</span><h2>Security work should create clarity—not just more findings.</h2></div><div><p className="large-copy">PDDG combines technical assessment, business-risk prioritization, and practical remediation guidance to help organizations make informed security decisions.</p><p>Its published mission emphasizes tailored cybersecurity solutions, protection of digital infrastructure and sensitive data, and operational continuity. The approach is designed to operate as an extension of the client’s security team.</p></div></div></section><section className="section muted"><div className="container"><SectionIntro eyebrow="Engagement principles" title="A client-focused, risk-driven way of working."/><div className="benefit-grid"><article><span className="card-number">01</span><h3>Defined authorization</h3><p>Scope, approved actions, constraints, and decision-makers are established before assessment activity.</p></article><article><span className="card-number">02</span><h3>Clear reporting</h3><p>Technical evidence and business context are separated so each audience can act effectively.</p></article><article><span className="card-number">03</span><h3>Practical priority</h3><p>Recommendations account for risk, operational impact, ownership, urgency, and feasible remediation.</p></article></div></div></section><Credentials/><section className="section"><div className="container two-col"><div><span className="eyebrow">Team expertise</span><h2>Disciplines represented without invented profiles.</h2><p>PDDG’s public materials support expertise across cybersecurity and IT, digital and physical assessment, cloud and application security, ethical hacking, awareness, monitoring, and policy review.</p></div><div className="expertise-cloud"><span>Application security</span><span>Penetration testing</span><span>Cloud security</span><span>Threat monitoring</span><span>Physical security</span><span>Security awareness</span><span>Governance</span><span>Wireless security</span></div></div></section></>;
}

export function ResourcesPage() {
  return <><PageHero eyebrow="Security resources" title="Practical guidance for planning, scoping, and acting on assessment work." copy="Use these resources to clarify objectives, compare service types, prepare stakeholders, and evaluate whether reporting will support real decisions." primary="View readiness checklist" primaryHref="/resources/cybersecurity-assessment-readiness-checklist" secondary="Request a sample report" secondaryHref="/request-a-sample-report" visual="policy"/><section className="section"><div className="container"><SectionIntro eyebrow="Resource library" title="Build context before the engagement begins."/><div className="resource-grid all-resources">{resources.map((r, i) => <Link href={`/resources/${r.slug}`} className="resource-card" key={r.slug}><div className={`resource-art art-${(i % 3) + 1}`}><span>{r.category}</span><i/><b>{String(i + 1).padStart(2, '0')}</b></div><div><span className="card-kicker">{r.read} read</span><h3>{r.title}</h3><p>{r.excerpt}</p><span className="card-link">Read resource <Icon name="arrow"/></span></div></Link>)}</div></div></section></>;
}

export function CaseStudiesPage() {
  return <><PageHero eyebrow="Case studies" title="Proof should be credible, appropriately sanitized, and approved for sharing." copy="PDDG does not publish unsupported client names, outcomes, or statistics. Sanitized engagement examples and sample deliverables may be discussed directly when appropriate." primary="Request a Sample Report" primaryHref="/request-a-sample-report" secondary="How sanitized examples work" secondaryHref="/case-studies/sanitized-engagement-example" visual="report"/><section className="section"><div className="container two-col"><div><span className="eyebrow">Evidence without overclaiming</span><h2>What a useful engagement example should explain.</h2></div><div className="number-list light-numbers"><span><b>01</b>The verified operating context and authorized objective</span><span><b>02</b>The assessment boundaries and methods appropriate to share</span><span><b>03</b>The type of risk identified without exposing sensitive detail</span><span><b>04</b>The decision or remediation path supported by the work</span></div></div></section><section className="section muted"><div className="container report-layout"><div><span className="eyebrow">Sample deliverables</span><h2>Review the structure before discussing sensitive examples.</h2><p>The preview uses synthetic data and does not represent a real client, system, finding, or outcome.</p><Link className="button" href="/request-a-sample-report">Request a Sample Report <span>↗</span></Link></div><ReportPreview/></div></section></>;
}

export function SanitizedCaseStudyPage() {
  return <><PageHero eyebrow="Sanitized engagement examples" title="Share the shape of the work without exposing a client or its systems." copy="This page explains how a properly approved engagement example can communicate assessment context, methods, decision value, and reporting quality without inventing or revealing sensitive facts." primary="Request an approved example" primaryHref="/request-a-sample-report" visual="report"/><section className="article-section section"><div className="container article-layout"><article><Breadcrumbs items={[{ label: 'Case Studies', href: '/case-studies' }, { label: 'Sanitized engagement examples' }]}/><h2>What can be shared responsibly</h2><p>A sanitized example should be based on a real, approved engagement and reviewed for confidentiality, contractual restrictions, sensitive architecture, personal data, and security implications. Removing a client name alone is not always sufficient.</p><h2>A useful structure</h2><ol><li><b>Context:</b> the general type of environment and the decision the organization needed to make.</li><li><b>Scope:</b> the broad categories of systems or controls assessed, without exposing defensive detail.</li><li><b>Method:</b> the authorized assessment approach at an appropriate level.</li><li><b>Finding themes:</b> categories of risk rather than exploitable instructions.</li><li><b>Decision value:</b> how the work informed prioritization, ownership, or remediation planning.</li></ol><h2>What this site deliberately avoids</h2><p>No client names, project outcomes, percentages, response commitments, or testimonials are shown unless they are verified and approved. The illustrative report elsewhere on this site uses synthetic content.</p></article><aside className="article-aside"><span className="eyebrow">Next step</span><h3>Need to evaluate report quality?</h3><p>Request a sample deliverable and discuss the level of executive and technical detail appropriate to your needs.</p><Link href="/request-a-sample-report" className="button">Request sample <span>↗</span></Link></aside></div></section></>;
}

export function FAQPage() {
  return <><PageHero eyebrow="Frequently asked questions" title="Clarify scope, safeguards, reporting, and next steps." copy="Cybersecurity engagements vary by objective and environment. These answers explain common planning considerations without promising a universal method or result." visual="signal"/><section className="section"><div className="container faq-layout"><SectionIntro eyebrow="Assessment planning" title="Questions decision-makers ask before an engagement."/><Accordion items={generalFaq}/></div></section></>;
}

export function ContactPage() {
  return <><PageHero eyebrow="Contact PDDG" title="Start with the concern, objective, or decision you need to address." copy="Use the demonstration form to preview the information PDDG may request. For live contact, call or email the verified details below." primary="Call 301-532-1463" primaryHref={`tel:${site.phoneHref}`} secondary="Email Info@pddg.io" secondaryHref={`mailto:${site.email}`} visual="signal"/><section className="section muted"><div className="container form-layout"><div><span className="eyebrow">General contact</span><h2>Tell PDDG what you are trying to understand.</h2><p>Appropriate details include the business objective, service area, general environment, timeline, and who will be involved. Do not submit sensitive findings or access information.</p><div className="contact-stack"><span><small>PHONE</small><a href={`tel:${site.phoneHref}`}>{site.phone}</a></span><span><small>EMAIL</small><a href={`mailto:${site.email}`}>{site.email}</a></span><span><small>ADDRESS</small>{site.address}</span><span><small>HOURS</small>{site.hours}</span></div></div><DemoForm kind="contact"/></div></section></>;
}

export function BookingPage() {
  return <><PageHero eyebrow="Security Fit Call" title="Determine the right assessment path before defining the scope." copy="A focused initial conversation can clarify the concern, desired outcome, environment, constraints, stakeholders, and information needed for a practical proposal." primary="Call PDDG" primaryHref={`tel:${site.phoneHref}`} secondary="General contact" secondaryHref="/contact" visual="target"><p className="hero-note"><Icon name="shield"/> The initial consultation is exploratory and does not itself constitute a cybersecurity assessment, incident-response engagement, or guarantee of service availability.</p></PageHero><section className="section"><div className="container form-layout"><div><span className="eyebrow">What to expect</span><h2>A scoping conversation—not a technical intake through a public form.</h2><div className="booking-points"><span><b>Who should attend</b><em>A decision-maker plus a technical, security, risk, or operations owner who understands the objective.</em></span><span><b>What will be discussed</b><em>Current concerns, desired decisions, environment context, applicable constraints, and possible assessment paths.</em></span><span><b>Useful preparation</b><em>A general asset view, relevant obligations, previous assessment context, stakeholders, and timing. Do not send sensitive data.</em></span><span><b>What happens afterward</b><em>If there is a potential fit, PDDG may request a secure scoping process and develop next-step recommendations.</em></span></div><div className="urgent-note"><b>Urgent incident?</b><p>This form is not an incident-response channel and does not guarantee availability. Call <a href={`tel:${site.phoneHref}`}>{site.phone}</a> to discuss time-sensitive needs.</p></div></div><DemoForm kind="booking"/></div></section></>;
}

export function SampleReportPage() {
  return <><PageHero eyebrow="Sample report request" title="Evaluate the reporting structure before you commit to an assessment." copy="Request a conversation about an illustrative or approved sanitized deliverable. Public examples never include real findings, client identities, or sensitive system details without approval." primary="Call PDDG" primaryHref={`tel:${site.phoneHref}`} visual="report"/><section className="section muted"><div className="container report-layout"><div><span className="eyebrow">Illustrative preview</span><h2>Executive clarity with technical depth beneath it.</h2><p>A scoped report may include risk-prioritized findings, evidence, business-impact context, remediation recommendations, owners, suggested timelines, and retesting status.</p></div><ReportPreview/></div></section><section className="section"><div className="container form-layout"><div><span className="eyebrow">Request details</span><h2>Explain the audience and decision your sample should support.</h2><p>This demonstration form sends no information. Use the verified phone or email for a live request.</p></div><DemoForm kind="report"/></div></section></>;
}

export function ResourceArticlePage({ slug }: { slug: string }) {
  const resource = resources.find(r => r.slug === slug)!;
  if (slug === 'cybersecurity-assessment-readiness-checklist') return <ReadinessChecklist/>;
  const content: Record<string, { intro: string; sections: [string, string, string[]?][] }> = {
    'penetration-testing-vs-vulnerability-assessment': { intro: 'Both services examine security exposure, but they answer different questions. A vulnerability assessment emphasizes breadth and prioritization; a penetration test adds controlled human validation of realistic attack paths.', sections: [['Choose vulnerability assessment when', 'You need a broad baseline across approved assets, want to identify common weaknesses, or need a prioritized view before deciding where deeper validation is warranted.', ['Inventory and baseline are primary goals', 'Coverage matters more than controlled exploitation', 'You need a structured remediation starting point']], ['Choose penetration testing when', 'You need to understand whether selected weaknesses can be used, how controls hold up across an attack path, or whether existing remediation has reduced realistic exposure.', ['Exploitability and attack paths matter', 'A customer or contract requires a defined test', 'You need human validation beyond automated discovery']], ['The combined path', 'Many organizations use assessment for breadth, penetration testing for depth, and vulnerability management to track risk reduction over time. The sequence should follow the decision—not a default package.']] },
    'what-a-penetration-test-report-should-include': { intro: 'A useful penetration-test report must work for two audiences: leaders deciding what matters and technical owners deciding what to fix.', sections: [['Executive context', 'The report should explain the objective, approved scope, key limitations, material risk themes, and the order in which leadership attention is needed.'], ['Technical evidence', 'Each finding should contain enough reproducible evidence for authorized owners to understand the affected component, condition, impact, and remediation direction.'], ['Prioritization and ownership', 'Severity should be explained with business context. Useful reporting connects findings to affected assets, responsible owners, suggested sequence, and any agreed validation status.']] },
    'prioritizing-vulnerabilities-by-business-risk': { intro: 'Technical severity is valuable, but it cannot describe the full consequence of a weakness in a specific organization.', sections: [['Add asset context', 'Ask whether the affected system supports a critical process, handles sensitive information, enables privileged access, or connects to higher-value environments.'], ['Evaluate likelihood and pathways', 'External exposure, exploit maturity, required access, attack complexity, and compensating controls influence how quickly a finding deserves attention.'], ['Sequence practical action', 'Ownership, maintenance windows, remediation dependencies, short-term safeguards, and validation requirements turn a ranking into an executable plan.']] },
    'wireless-security-weaknesses': { intro: 'Wireless risk extends beyond access-point configuration. It includes identity, segmentation, physical coverage, guest access, connected devices, monitoring, and ownership.', sections: [['Inventory what is actually present', 'Compare approved access points, networks, controllers, and Bluetooth-enabled devices with what can be observed in the environment.'], ['Validate separation', 'Review whether guest, staff, device, and operational networks are separated as intended and whether administration paths are appropriately controlled.'], ['Connect wireless and physical controls', 'Signal coverage, device location, shared spaces, facility access, and unmanaged equipment can create risk that a wired inventory does not show.']] },
    'building-an-effective-security-awareness-program': { intro: 'Annual completion alone does not show that people can recognize and report risk in real work.', sections: [['Start with role decisions', 'Identify the security decisions made by executives, administrators, finance, frontline staff, technical teams, and other meaningful groups.'], ['Use relevant reinforcement', 'Combine concise learning, practical examples, manager support, safe simulations where appropriate, and clear reporting paths.'], ['Measure behavior carefully', 'Track useful trends such as reporting, recurring themes, knowledge gaps, and process friction without treating a single click rate as the whole program.']] }
  };
  const article = content[slug];
  return <><PageHero eyebrow={resource.category} title={resource.title} copy={resource.excerpt} primary="Discuss an assessment" primaryHref="/book-a-security-fit-call" visual="policy"/><section className="article-section section"><div className="container article-layout"><article><Breadcrumbs items={[{ label: 'Resources', href: '/resources' }, { label: resource.title }]}/><p className="article-intro">{article.intro}</p>{article.sections.map(([title, text, bullets]) => <section key={title}><h2>{title}</h2><p>{text}</p>{bullets && <ul>{bullets.map(b => <li key={b}>{b}</li>)}</ul>}</section>)}<div className="article-disclaimer"><b>Planning guidance</b><p>This resource is educational and does not replace a scoped professional assessment, legal advice, or a compliance determination.</p></div></article><aside className="article-aside"><span className="eyebrow">Need a defined scope?</span><h3>Connect the objective to the right assessment.</h3><p>Discuss the environment, decision, constraints, and next steps with PDDG.</p><Link href="/book-a-security-fit-call" className="button">Book a fit call <span>↗</span></Link></aside></div></section></>;
}

function ReadinessChecklist() {
  return <><PageHero eyebrow="Planning checklist" title="Cybersecurity Assessment Readiness Checklist" copy="Organize the objectives, systems, people, approvals, evidence, and deliverables that make assessment scoping more precise and useful." primary="Discuss your readiness" primaryHref="/book-a-security-fit-call" visual="checklist"/><section className="section"><div className="container checklist-layout"><div className="checklist-intro"><Breadcrumbs items={[{ label: 'Resources', href: '/resources' }, { label: 'Assessment Readiness Checklist' }]}/><span className="eyebrow">12 planning areas</span><h2>Prepare the information that improves scope and reduces avoidable delay.</h2><p>Do not submit sensitive versions of these materials through a public form. Use an approved secure channel after contracting and authorization.</p></div><div className="readiness-list">{readinessItems.map(([title, copy], i) => <article key={title}><span>{String(i + 1).padStart(2, '0')}</span><div><h3>{title}</h3><p>{copy}</p></div><label><input type="checkbox"/><span className="sr-only">Mark {title} complete</span></label></article>)}</div><div className="article-disclaimer"><b>Important</b><p>This checklist supports planning. It does not replace a professional assessment, legal analysis, regulatory interpretation, or formal authorization.</p></div></div></section></>;
}

export function LegalPage({ kind }: { kind: 'privacy' | 'terms' | 'accessibility' }) {
  const data = {
    privacy: { eyebrow: 'Legal', title: 'Privacy Policy', intro: 'This demonstration reproduces the core privacy commitments published by PDDG and explains the current demo-form limitation.', sections: [['Information you provide', 'PDDG may collect contact information and other details voluntarily provided through connected channels. This demonstration site does not transmit or store form entries.'], ['How information may be used', 'Information may be used to respond to inquiries, provide services, improve website functionality, communicate with consent, prevent misuse, and meet legal obligations.'], ['Sharing and security', 'PDDG’s published policy states that personal information is not sold or rented, while acknowledging limited sharing with service providers, legal authorities, or in a business transfer. Reasonable safeguards do not guarantee absolute security.'], ['Your choices', 'Depending on location and applicable law, individuals may have rights related to access, correction, deletion, objection, portability, or withdrawal of consent.'], ['Contact', `Privacy questions may be directed to ${site.email} or ${site.address}. The source policy published by PDDG lists an effective date of January 15, 2025.`]] },
    terms: { eyebrow: 'Legal', title: 'Terms and Conditions', intro: 'These website terms explain the limited purpose of this demonstration and do not create a cybersecurity engagement.', sections: [['Informational use', 'Content is provided for general information and assessment planning. It is not legal advice, a compliance determination, incident-response service, or a substitute for a signed engagement.'], ['No guarantees', 'Cybersecurity risk cannot be eliminated. Nothing on this website promises complete protection, guaranteed compliance, incident prevention, service availability, or a specific outcome.'], ['Authorization required', 'Security testing must be explicitly authorized in writing and limited to the agreed systems, methods, identities, facilities, and time windows.'], ['Intellectual property', 'PDDG names, marks, original content, and approved credential graphics remain subject to their respective ownership and permitted use.'], ['Contact', `Questions about these terms may be directed to ${site.email}. These demonstration terms should be reviewed by PDDG’s legal counsel before replacing approved production terms.`]] },
    accessibility: { eyebrow: 'Accessibility', title: 'Accessibility Statement', intro: 'PDDG aims to provide an inclusive website experience aligned with WCAG 2.2 Level AA practices.', sections: [['Measures included', 'The site uses semantic structure, keyboard-accessible navigation, visible focus states, descriptive links, labeled forms, responsive layouts, reduced-motion support, and alternatives for visual diagrams.'], ['Known limitation', 'The forms are intentionally in demonstration mode and do not transmit information. This limitation is communicated before submission and in the confirmation state.'], ['Feedback', `If you encounter an accessibility barrier, contact ${site.email} or call ${site.phone}. Include the page and the difficulty encountered without sending sensitive security information.`], ['Ongoing improvement', 'Accessibility is an ongoing practice. Content, browser behavior, assistive technology, and future integrations should be reviewed as the site changes.']] }
  }[kind];
  return <><section className="legal-hero dark-section"><div className="container"><span className="eyebrow light">{data.eyebrow}</span><h1>{data.title}</h1><p>{data.intro}</p></div></section><section className="legal-body section"><div className="container article-layout"><article>{data.sections.map(([title, copy]) => <section key={title}><h2>{title}</h2><p>{copy}</p></section>)}</article><aside className="article-aside"><span className="eyebrow">Contact</span><h3>Pinnacle Digital Defense Group</h3><p>{site.address}</p><a href={`mailto:${site.email}`}>{site.email}</a><a href={`tel:${site.phoneHref}`}>{site.phone}</a></aside></div></section></>;
}

export function ThankYouPage({ kind }: { kind: 'contact' | 'security-fit-call' | 'resource-request' }) {
  const title = kind === 'contact' ? 'Contact request' : kind === 'security-fit-call' ? 'Security Fit Call request' : 'Resource request';
  return <section className="confirmation-page dark-section"><div className="confirmation-card"><span className="result-icon">✓</span><span className="eyebrow light">Demonstration confirmation</span><h1>{title} preview complete.</h1><p>No information was sent or stored. The demonstration forms on this site are not connected to a live submission system.</p><div className="hero-actions"><a className="button" href={`tel:${site.phoneHref}`}>Call {site.phone}</a><a className="button button-ghost" href={`mailto:${site.email}`}>Email {site.email}</a></div><Link href="/" className="text-link light-link">Return to homepage <Icon name="arrow"/></Link></div></section>;
}
